### ISSUE TITLE
Mega link encrypted

### ISSUE THREAD

**Issue by corinahmariah** [zhongjiedong/Tsukiro#1]
![image](https://user-images.githubusercontent.com/83296735/116268145-b5f2a880-a785-11eb-997d-2ebfbea78551.png)
the link https://mega.nz/file/irQGQbyJ#OWnNk9yND1_rDtoPfe0V8hWKI3bXeJ2lk1x_Tqdzufs

**Comment by zhongjiedong** [comment]
try this https://mega.nz/file/irQGQbyJ#OWnNk9yND1_rDtoPfe0V8hWKI3bXeJ2Ik1x_Tqdzufs

**Comment by corinahmariah** [comment]
this one worked, thanks!
