### ISSUE TITLE
Error loading ESPs and ESM

### ISSUE THREAD

**Issue by Iceman2819** [zhongjiedong/Tsukiro#100]
### What happened?

Upon launching the game after following the guide and installing, the load in screens are buggy and don't match the displayed ones in the guide, along with a few errors of partial original skyrim menu being available. Upon attempting to continue the save file it pops up that certain ESPs and ESMs are not available. In MO2 though they are shown as enabled.

### Modlist version

1.1.74

**Comment by zhongjiedong** [comment]
This isn't a bug with the modlist but more with your setup. Check you have all pre-requisites
