### ISSUE TITLE
One File Just updated Billy's Animations

### ISSUE THREAD

**Issue by Bountyhunter0** [zhongjiedong/Tsukiro#102]
I got everything downloaded and everything was working good until just one mod Billyy's Animations on lovers lab. Looks like they just updated to 5.6 and I need the 5.5 version for Wabbajack to successfully download and its the very last thing I need. If there is any work around for this it would be greatly appreciated. Thank you!!

**Comment by zhongjiedong** [comment]
try in about an hour, download 5.6 and it should work
