### ISSUE TITLE
There's a new version of SLAL_Billyy_Animations and the previous version needed by Wabbajack is not there and it doesn't accept the new one.

### ISSUE THREAD

**Issue by DaeXen** [zhongjiedong/Tsukiro#104]
### What happened?

Basically the title.

### Modlist version

1.1.74

**Comment by SlavishCat** [comment]
How did you get it working?

**Comment by DaeXen** [comment]
> How did you get it working?

I found the Discord (which was kinda hard lol). Here's the link: https://discord.gg/jolly-coop

Then the mod is in the pinned messages of the support channel
