### ISSUE TITLE
Billy's Animations updated

### ISSUE THREAD

**Issue by CousinRed** [zhongjiedong/Tsukiro#106]
Billy's Animations (download from Lover's Lab) has been updated as of May 2... I think it's version 5.6 now, 5.5 isn't available and Tsukiro won't install...

Please fix and thanks for all your hard work!

**Comment by zhongjiedong** [comment]
post your log here

**Comment by CousinRed** [comment]
[Wabbajack.current.log](https://github.com/zhongjiedong/Tsukiro/files/8627851/Wabbajack.current.log)

**Comment by ZombieAndrew** [comment]
Yeah I also have this problem

**Comment by zhongjiedong** [comment]
should be fixed now try again
