### ISSUE TITLE
Bug report list for 1.0 preview

### ISSUE THREAD

**Issue by Seatmeister** [zhongjiedong/Tsukiro#108]
### What happened?

So I visited all of the nine holds on some minor places, entered every cell looked at every npc to see, if i find some bugs. Here are some, I might have missed things 
- Npc Appearance bug/others
1. Lucien Flavius Face bug
https://imgur.com/a/AzDBs7S
2. Skjor, Kodlak Whitemane and Torvar floating Hands bug
https://imgur.com/a/iDxQBMS
3. Aia Arria missmatched head and body color
https://imgur.com/a/dzyySpv
4. When encountering an npc for the first time, sometimes darkface bug or are naked, fixed by reloading game(i suppose). Some examples:
https://imgur.com/a/zg8LRVo
- Texture missing bug/others
1. Missing pillar texture in Dragonsreach and Jarls Quarters in Whiterun (probalby fixed by latest update)
https://imgur.com/a/438i7jt
2. Missing texture in Hall of Dead in Whiterun 
https://imgur.com/a/igCXF1V
3. Invisible floor in Arch Mage's Quarters in College of Winterhold ( seen when entering doorframe)
https://imgur.com/a/FXjvhyj
4. Door into the void in Proudspire Manor in Solitude (second floor)
https://imgur.com/a/5CF7rBT
5. Floating Sign in Kynesgrove outside the Inn
https://imgur.com/a/HhLlItS
-Some objects i'm not sure about, if they are intended
1. Two bridges outside Markarth
https://imgur.com/a/UZyp066
2. Grass on floor inside Hall of Kyne in Ivarstead
https://imgur.com/a/cjaHClu

### Modlist version

1.0 preview

**Comment by zhongjiedong** [comment]
fixed in 1.0
