### ISSUE TITLE
Missing armor textures/meshes or invisible. Preview 1.01

### ISSUE THREAD

**Issue by Seatmeister** [zhongjiedong/Tsukiro#109]
### What happened?

Some armors that I found which are missing stuff like textures or mesh
- Crusader Heavy Armor each piece is invisible, Mod: DCR_KingCrusaderMegaPack
https://imgur.com/a/OuijJL0
- RYANREOS Elf Paladin all pieces missing textures, Mod: immyneedscake RyanReos Elf Paladin
https://imgur.com/a/CPX3R0b
- RYANREOS High Priestess Armor Corrupted and Inquisitor not showing, Normal High Priestess is showing, Mod: RyanReos High Priestess
https://imgur.com/a/yQEnOsu
- Some pieces of the Knight Armor are invisible, Mod: Knight of The Village Set
https://imgur.com/a/eyj4RNh 

### Modlist version

preview 1.01

**Comment by zhongjiedong** [comment]
armours consoled in, not relevant
