### ISSUE TITLE
Lovelabs

### ISSUE THREAD

**Issue by SirAart** [zhongjiedong/Tsukiro#11]
It fails to download a collection of mods from lovelabs. I'm logged in to the site and after some trying I've manually downloaded some of the missing ones, but the installation still fails due to missing mods. Am I missing something or are the links just busted somehow?
[Wabbajack.current.log](https://github.com/zhongjiedong/Tsukiro/files/6681954/Wabbajack.current.log)

**Comment by Corbillion** [comment]
In the settings on Wabbajack are you logged into lovers lab?

**Comment by SirAart** [comment]
Yes, I am.

**Comment by Corbillion** [comment]
If you copy the URL for the mods from the log file into a browser does it resolve?  Your getting forbidden errors in the log so I still think its linked to login, they work for me.

Make sure you have verified your Loverslab email address too.

**Comment by xaanson** [comment]
I'm Having a similar issue, I've logged into loverslab through wabbajack and checked that I have verified my email. It gives me the error that the download is broken or "(DeprecatedLoversLabDownloader+State|)" on all of the lovers lab downloads. When I check the Log Files that it gives me it doesn't give me any urls. Have either of you found what's going on with the downloader?
[Wabbajack.current.log](https://github.com/zhongjiedong/Tsukiro/files/6713272/Wabbajack.current.log)

**Comment by ItsJustG** [comment]
Same here, failing to download Loverslab stuff, even though, logged into Loverslab on Wabbajack. Tried the slow connection workaround as well.

**Comment by xaanson** [comment]
I'm going through loverslab and  finding all of the files so far able to download and when I checked to see if it recognizes them as the files it needs it does. I'll grab all of the missing downloads and see if i cant share it somewhere.

**Comment by ItsJustG** [comment]
Any idea when this will be fixed?

**Comment by ItsJustG** [comment]
I have unloaded, logged out, uninstalled everything relating to SSE. I have reinstalled, logged back into Loverslab and Nexus through Wabbajack. Ill see what happens. I can download stuff outside of WJ from loverslab no problem. Its only when trying to install this mod pack.

**Comment by zhongjiedong** [comment]
modlist is down atm pending update since wabbajack did a big update.

**Comment by ItsJustG** [comment]
Oh wow, that explains it. Thanks
