### ISSUE TITLE
Smooth Motion Pack SE 5.3.3

### ISSUE THREAD

**Issue by Jeebss** [zhongjiedong/Tsukiro#110]
### What happened?

5.1 - Validating Game ESMs
5.12 - Creating Output Folders
5.74 - Optimizing ModList
5.74 - Optimizing ModList directives
8.33 - Looking for files to delete
8.35 - Cleaning empty folders
9.17 - Looking for unmodified files
9.8 - Updating ModList
9.8 - Optimized 198599 directives to 198599 required
9.84 - Hashing Archives
9.84 - Looking for files to hash
10.03 - Found 1228 total files, 1018 matching filesize
10.22 - Downloading Missing Archives
10.22 - Missing 1 archives
10.22 - Getting Nexus API Key, if a browser appears, please accept
10.23 - Loading server whitelist
10.43 - Loaded permissions for 675 servers and 299 Google Drive files
10.43 - Getting upgrades list
10.64 - File hash check (-42) db84c2145f9d01f15649807be67c7f459c2f8c19d042a33b9466170637130eef
10.67 - Downloading Smooth Motion Pack SE 5.3.3.FOMOD
11.24 - Hashed download is incorrect
11.24 - Loading for alternative to EX/MxhndsFE=
11.24 - No alternative for EX/MxhndsFE= could be found
11.29 - Hashing Remaining Archives
11.29 - Looking for files to hash
11.37 - Found 1228 total files, 1018 matching filesize
**11.55 - Unable to download Smooth Motion Pack SE 5.3.3.FOMOD (GoogleDriveDownloader+State|1MLyn1f44aEBlO0NNJGDLA0OXwDvk7hvD)
11.55 - Cannot continue, was unable to download one or more archives
11.55 - File hash check (-42) db84c2145f9d01f15649807be67c7f459c2f8c19d042a33b9466170637130eef**
11.57 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\AInstaller.cs:line 71
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass88_0.<<-ctor>b__78>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 391
11.72 - File hash check (-42) db84c2145f9d01f15649807be67c7f459c2f8c19d042a33b9466170637130eef

### Modlist version

Latest version of the mod.

Also my apologies if this is a bad place to post this. If I should post this elsewhere please let me know. Thanks for your time.

**Comment by Jeebss** [comment]
I just realized one of my issues, I will post again of I cannot get it working.

**Comment by Jeebss** [comment]
0.26 - Wabbajack Build - aa36c5996492336a142f2e355e67c204ba806dc5
0.26 - Running in E:\Wabbajack\2.5.3.15
0.28 - Detected Windows Version: 10.0.19044.0
0.28 - System settings - (32GB RAM) (24.8GB Page), Display: 1920 x 1080 (10.9GB VRAM - VideoMemorySizeMb=10240)
0.29 - Getting new Wabbajack version list
0.34 - Steam: ACF Manifest at D:\SteamLibrary\steamapps\appmanifest_1245620.acf does not contain a value with key appid
0.34 - Steam: ACF Manifest at D:\SteamLibrary\steamapps\appmanifest_1245620.acf does not contain a value with key name
0.34 - Steam: ACF Manifest at D:\SteamLibrary\steamapps\appmanifest_1245620.acf does not contain a value with key installdir
0.34 - Steam: ACF Manifest at D:\SteamLibrary\steamapps\appmanifest_1245620.acf does not contain a value with key LastUpdated
0.34 - Steam: ACF Manifest at D:\SteamLibrary\steamapps\appmanifest_1245620.acf does not contain a value with key SizeOnDisk
0.34 - Steam: ACF Manifest at D:\SteamLibrary\steamapps\appmanifest_1245620.acf does not contain a value with key BytesToDownload
0.34 - Steam: ACF Manifest at D:\SteamLibrary\steamapps\appmanifest_1245620.acf does not contain a value with key BytesDownloaded
0.35 - Steam: ACF Manifest at D:\SteamLibrary\steamapps\appmanifest_1245620.acf does not contain a value with key BytesToStage
0.35 - Steam: ACF Manifest at D:\SteamLibrary\steamapps\appmanifest_1245620.acf does not contain a value with key BytesStaged
0.35 - Steam: ACF Manifest at D:\SteamLibrary\steamapps\appmanifest_221100.acf does not contain a value with key BytesToDownload
0.35 - Steam: ACF Manifest at D:\SteamLibrary\steamapps\appmanifest_221100.acf does not contain a value with key BytesDownloaded
0.35 - Steam: ACF Manifest at D:\SteamLibrary\steamapps\appmanifest_221100.acf does not contain a value with key BytesToStage
0.35 - Steam: ACF Manifest at D:\SteamLibrary\steamapps\appmanifest_221100.acf does not contain a value with key BytesStaged
0.36 - Steam: Found game 3DMark (223850) at "E:\SteamLibrary\steamapps\common\3DMark"
0.36 - Steam: Found game Darkest Dungeon® (262060) at "E:\SteamLibrary\steamapps\common\DarkestDungeon"
0.36 - Steam: Found game Black Desert (582660) at "E:\SteamLibrary\steamapps\common\Black Desert Online"
0.36 - Steam: Found game Sid Meier's Civilization V (8930) at "E:\SteamLibrary\steamapps\common\Sid Meier's Civilization V"
0.36 - Steam: Found game Steamworks Common Redistributables (228980) at "C:\Program Files (x86)\Steam\steamapps\common\Steamworks Shared"
0.36 - Steam: Found game ELDEN RING (1245620) at "D:\SteamLibrary\steamapps\common\ELDEN RING"
0.36 - Steam: Found game Hollow Knight (367520) at "D:\SteamLibrary\steamapps\common\Hollow Knight"
0.36 - Steam: Found game Wallpaper Engine (431960) at "D:\SteamLibrary\steamapps\common\wallpaper_engine"
0.36 - Steam: Found game Nioh: Complete Edition (485510) at "D:\SteamLibrary\steamapps\common\Nioh"
0.36 - Steam: Found game Counter-Strike: Global Offensive (730) at "D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive"
0.36 - Steam: Found game Outward (794260) at "D:\SteamLibrary\steamapps\common\Outward"
0.36 - Steam: Found game Sea of Thieves (1172620) at "D:\SteamLibrary\steamapps\common\Sea of Thieves"
0.36 - Steam: Found game The Elder Scrolls V: Skyrim Special Edition (489830) at "E:\SteamLibrary2\steamapps\common\Skyrim Special Edition"
0.36 - Steam: Found game Steamworks Common Redistributables (228980) at "c:/program files (x86)/steam\steamapps\common\Steamworks Shared"
0.36 - GOG: GOG was not found in the registry
0.36 - BethNet: Unable to open Registry Keys SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net and SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net
0.36 - EGS: Unable to open Registry Key SOFTWARE\Epic Games\EOS
0.36 - Origin: LocalContent directory at C:\ProgramData\Origin\LocalContent does not exist
0.96 - Wabbajack Version: 2.5.3.15
1.19 - Build server is alive
1.2 - File hash check (-42) db84c2145f9d01f15649807be67c7f459c2f8c19d042a33b9466170637130eef
1.22 - Build server is alive
1.22 - File hash check (-42) db84c2145f9d01f15649807be67c7f459c2f8c19d042a33b9466170637130eef
8.49 - Starting to install Tsukiro
8.5 - Cleaning VFS, this may take a bit of time
8.53 - Starting Installer Task
8.53 - Installation has Started
8.53 - File hash check (-42) db84c2145f9d01f15649807be67c7f459c2f8c19d042a33b9466170637130eef
8.69 - Configuring Processor
8.69 - Install Folder: E:\Tsukiro
8.69 - Downloads Folder: E:\Tsukiro\downloads
8.69 - Game Folder: E:\SteamLibrary2\steamapps\common\Skyrim Special Edition
8.69 - Wabbajack Folder: E:\Wabbajack\2.5.3.15
8.7 - Drive watcher is starting. Will warn at 8GB and error at 4GB
8.7 - Starting Drive watcher on E:\ currently 357.4GB free out of 894.2GB
8.7 - Validating Game ESMs
8.71 - Creating Output Folders
9.37 - Optimizing ModList
9.38 - Optimizing ModList directives
12.04 - Looking for files to delete
12.06 - Cleaning empty folders
12.97 - Looking for unmodified files
13.61 - Updating ModList
13.61 - Optimized 198599 directives to 198599 required
13.65 - Hashing Archives
13.65 - Looking for files to hash
13.72 - Found 1036 total files, 1016 matching filesize
204.24 - Downloading Missing Archives
204.24 - Missing 1 archives
204.24 - Getting Nexus API Key, if a browser appears, please accept
204.26 - Loading server whitelist
204.44 - Loaded permissions for 675 servers and 299 Google Drive files
204.44 - Getting upgrades list
204.55 - File hash check (-42) db84c2145f9d01f15649807be67c7f459c2f8c19d042a33b9466170637130eef
204.57 - Downloading Smooth Motion Pack SE 5.3.3.FOMOD
205.13 - Hashed download is incorrect
205.13 - Loading for alternative to EX/MxhndsFE=
205.13 - No alternative for EX/MxhndsFE= could be found
205.2 - Hashing Remaining Archives
205.2 - Looking for files to hash
205.3 - Found 1036 total files, 1016 matching filesize
205.5 - Unable to download Smooth Motion Pack SE 5.3.3.FOMOD (GoogleDriveDownloader+State|1MLyn1f44aEBlO0NNJGDLA0OXwDvk7hvD)
205.5 - Cannot continue, was unable to download one or more archives
205.5 - File hash check (-42) db84c2145f9d01f15649807be67c7f459c2f8c19d042a33b9466170637130eef
205.51 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\AInstaller.cs:line 71
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass88_0.<<-ctor>b__78>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 391
205.64 - File hash check (-42) db84c2145f9d01f15649807be67c7f459c2f8c19d042a33b9466170637130eef

Still not working. I am now out of ideas and would appreciate feedback, thank you.

**Comment by largemonron** [comment]
https://github-wiki-see.page/m/zhongjiedong/Tsukiro/wiki/Commonly-failing-downloads

You can find the manual download for Smooth Motion Pack SE 5.3.3.FOMOD here.

**Comment by Jeebss** [comment]
Thanks I didn't see that @largemonron

**Comment by Jeebss** [comment]
@largemonron I didn't see your comment until today. I worked. Your a saint. Thanks for the assistance.
