### ISSUE TITLE
GS_SLAL SE Creatures and GS_SLAL SE updated

### ISSUE THREAD

**Issue by NotASpammy** [zhongjiedong/Tsukiro#112]
### What happened?

GS_SLAL SE Creatures and GS_SLAL SE got updated and it gives me error when i try to install
Screenshot: https://ibb.co/mcMj425

### Modlist version

1.1.74 (latest one in wabbajack)

**Comment by ndpowell** [comment]
I had this issue too, as a workaround you can download the zips manually from Gunslicer's Patreon:
https://www.patreon.com/posts/slal-creatures-62822632

**Comment by NotASpammy** [comment]
> 

Thanks

**Comment by Draemor555** [comment]
I had this issue too, as a workaround you can download the zips from Gunslicer's Patreon:
https://www.patreon.com/posts/slal-creatures-62822632

Sorry, had to edit
