### ISSUE TITLE
Gs slal not downloading on wabbajack

### ISSUE THREAD

**Issue by OniBlade1** [zhongjiedong/Tsukiro#114]
### What happened?

Apparently there is a newer version for it please update it.

### Modlist version

Version:1.1.74

**Comment by nh60211as** [comment]
I followed the approcah in  
https://github.com/zhongjiedong/Tsukiro/issues/112#issuecomment-1145743984
as a workaround.

**Comment by OniBlade1** [comment]
> I followed the approcah in [#112 (comment)](https://github.com/zhongjiedong/Tsukiro/issues/112#issuecomment-1145743984) as a workaround.

Thanks that worked for me.
