### ISSUE TITLE
Cannot continue, was unable to download one or more archives

### ISSUE THREAD

**Issue by catchra** [zhongjiedong/Tsukiro#119]
### What happened?

@zhongjiedong 
after looking into #118  i ran into this error `Cannot continue, was unable to download one or more archives` the log is attached
[Wabbajack.current.log](https://github.com/zhongjiedong/Tsukiro/files/8949094/Wabbajack.current.log)

### Modlist version

1.1.74

**Comment by zhongjiedong** [comment]
you're downloading some old af version, get the latest one
