### ISSUE TITLE
Wabbajack hosted files won't download

### ISSUE THREAD

**Issue by VikingZatoichi** [zhongjiedong/Tsukiro#12]
several downloads hosted on the Wabbajack site wouldn't complete,

Unable to download bodyslideoutput0.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/bodyslideoutput0.7z_7878a94e-72b5-47e0-b104-a07c9f218b56)
3959.68 - Unable to download bodyslideoutput4.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/bodyslideoutput4.7z_0941b0ce-9857-4604-8558-f3c2f975a20b)
3959.68 - Unable to download bodyslideoutput6.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/bodyslideoutput6.7z_b49b6354-09a6-47a0-a9b6-4d5676abed60)
3959.69 - Unable to download EVW facegen021.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/EVW facegen021.7z_a68b65d5-119c-40ae-b230-33d00e9c97eb)
3959.69 - Unable to download tsukirodyndolod043.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/tsukirodyndolod043.7z_eccaa385-1db2-46b2-b22c-7b7d1c1697fb)
3959.69 - Unable to download New cloud YOU NEED THAT.rar (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/New cloud YOU NEED THAT.rar_726ea70c-89b4-4d46-87c4-69e63d897299)
3959.69 - Unable to download Skyrim.Priority.SE.zip (HTTPDownloader+State|https://github.com/Erstori/FallrimPriority/releases/download/2.2.1/Skyrim.Priority.SE.zip)

[Wabbajack.current.log](https://github.com/zhongjiedong/Tsukiro/files/6682727/Wabbajack.current.log)

**Comment by zhongjiedong** [comment]
You should try the network workaround option in WJ

**Comment by phsharkey** [comment]
Sorry to be an ignorant newbie but could you please expand upon, "network workaround option in WJ."?   Thanks.

**Comment by zhongjiedong** [comment]
https://i.ibb.co/FDPDrfk/Discord-VPN.png

**Comment by phsharkey** [comment]
figured it out.  Not sure the problem is solved but I checked the workaround button and fired up my VPN.  Let's see what happens.

**Comment by VikingZatoichi** [comment]
Thanks!  the files are downloaded and installing now.  Thank you for showing me that setting, I didn't know that's what it was for.
