### ISSUE TITLE
Tsukiro down for Maintenance 

### ISSUE THREAD

**Issue by RKRJR13** [zhongjiedong/Tsukiro#121]
### What happened?

I see that Tsukiro is down for maintenance. Is there an ETA for when it will be back up for download? 

### Modlist version

I see that Tsukiro is down for maintenance. Is there an ETA for when it will be back up for download?

**Comment by hunterman34** [comment]
@RKRJR13 You can download the release manually and install from disk. You just have to download the high poly head manually from vectorplexis as vectorplexus is down, and then the download and installation works just fine.
