### ISSUE TITLE
Pistol and Rifle of Glenmoril not working as intended

### ISSUE THREAD

**Issue by Zvarrit** [zhongjiedong/Tsukiro#124]
### What happened?

When using pistol in right hand they attack like a sword, when using in left hand nothing happen, they didn't shoot, and prevent you for attacking even with a weapon in right hand.
When using rifle they use bow animation.

### Modlist version

1.0 preview

**Comment by zhongjiedong** [comment]
fixed in 1.0 but guns will only work properly in left hand.
