### ISSUE TITLE
Yamate Kudasai Captures not working

### ISSUE THREAD

**Issue by PotatoKnight** [zhongjiedong/Tsukiro#125]
### What happened?

I've been told this is a known issue with the modlist and that Yamate is being revamped. I've also been told that people don't report things on Github, so here I am, reporting it!

When capturing enemies via Yamate Kudasai, they, _at least_ sometimes (more testing needed) do not come back as the same NPC. For example, I captured a Spellsword and when summoning them back via Numpad -, they returned as a Necromancer, who became hostile as they were no longer tied up and had to be defeated again. Further, they had new equipment, as if they were an entirely new NPC, unsurprisingly.

### Modlist version

The Preview Build.

**Comment by zhongjiedong** [comment]
fixed in 1.01
