### ISSUE TITLE
Bugs encountered in Preview 1.0

### ISSUE THREAD

**Issue by Miss-Corruption** [zhongjiedong/Tsukiro#126]
### What happened?

Items:

- Potions occasionally do not heal past a certain amount of health. The potion will be consumed but you can't heal over for example 25% of Max HP. You'll gain nothing. Healing spells work.

- Sometimes the animation for drinking a potion plays without something in your hand. No potion will be consumed but you don't heal either.

Controller:

- Cannot charge soul stones in Inventory, this can be fixed by editing the `controlmap.txt` in `Tsukiro\mods\The Ultimate Control Scheme\Interface\Controls\PC`. Changing `'!0,Shout'` to `'0x0200'` for ChargeItem fixes it. It should look like this:
`// Inventory
ChargeItem    !0,Wait    !0,Wait    0x0200        0    0    0    0x8`

- Sprinting doesn't work. Changing the key bind from R1/RB to anything else doesn't solve this either.

Gameplay:

- Sekiro Deathblow stays on the enemy for multiple hits, is that intended?

- Fast Travel sometimes bugs out on sign posts. You cannot fast travel anymore.

- Reading a book or letters sometimes flicks around the camera.

- While they do no damage, walking on bones accelerates you with the force of physics.

Misc:

- Katana, when nude, still wears underwear. Was that intended?

My Specs:
[DxDiag.txt](https://github.com/zhongjiedong/Tsukiro/files/9262475/DxDiag.txt)

### Modlist version

Preview 1.0

**Comment by zhongjiedong** [comment]
Cannot reproduce any of this, signs are fixed, bones are just bethesda physics, camera is fixed, Katana should now be nude
