### ISSUE TITLE
Missing finger textures on Gauntlets

### ISSUE THREAD

**Issue by LightAdept** [zhongjiedong/Tsukiro#131]
### What happened?

The Wolf Heavy Bikini Gauntlet II has two fully covered fingers, and the rest should be fingerless gloves-esque. Most likely the same issue happens on the light version, did not test.

![image](https://user-images.githubusercontent.com/2672563/184511445-219b1238-147d-4942-909e-800d7aa9f86e.png)

i made a github account just for this, happy now?! :P

### Modlist version

1.0.2

**Comment by zhongjiedong** [comment]
fixed in 1.03
