### ISSUE TITLE
First Person Hands disappear after opening map in dungeons

### ISSUE THREAD

**Issue by TheAwesomeGem** [zhongjiedong/Tsukiro#135]
### What happened?

Upon opening the map inside a dungeon, the first person hands just disappears visually. You can still see the streak and particle when attacking but no hands or weapons. After exiting the dungeon, opening both local/world map doesn't make the hands disappear. Only started happening after updating to 1.0.3. This issue does not occur in other interiors like shops, bars, etc.

After removing ImprovedCameraSE, this issue is fixed. It appears to be an issue with that mod.

### Modlist version

1.0.3 and 1.0.4

**Comment by TheAwesomeGem** [comment]
This issue is still reproducible in 1.0.4.

**Comment by zhongjiedong** [comment]
fixed in 1.0.5
