### ISSUE TITLE
waiting while standing

### ISSUE THREAD

**Issue by CDRShepard96** [zhongjiedong/Tsukiro#14]
cant wait while standing, and not sure if there is a setting for it some place, iv looked in all of the mod settings but cant find it.

**Comment by zhongjiedong** [comment]
sit down

**Comment by CDRShepard96** [comment]
kinda hard to sit down when in the woods at night, cant see shit XD

**Comment by zhongjiedong** [comment]
guess u need to plan a bit better next time eh
