### ISSUE TITLE
Celes Rogue Cuirass issue

### ISSUE THREAD

**Issue by c-mart-88** [zhongjiedong/Tsukiro#142]
### What happened?

Celes Rogue Cuirass looks wonky when worn. Does not fit to body and skin contorts. was found in dragur ruins, not added through console
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2022 08 19 - 13 44 15 100](https://user-images.githubusercontent.com/111605334/185689323-3ef8716e-5911-481d-8154-e1f281e0857b.png)
.

### Modlist version

On Tsukiro v 1.0.5

**Comment by zhongjiedong** [comment]
Can I ask if you used any of the following sliders in racemenu:

UNPB Chapi - For it can be imitated by other sliders
UNPB Oppai v1 - For it's so similar to UNPB Oppai v3.2 and it can be imitated by other sliders
UNPF Series - For these sliders are ugly as hell.
CNHF + CNHF bonus - It's not used. Not popular
Venus - It's not used. Not popular
Seraphim - For it can be imitated by other sliders
UNPK Bonus - For it can be imitated by other sliders
UNPSH - For it can be imitated by other sliders
DreamGirl - For it can be imitated by other sliders

**Comment by c-mart-88** [comment]
All of the sliders in raceemenu are set to 0. The only ones I have changed are the ones involving the butt, waist, thighs, and calves.

**Comment by zhongjiedong** [comment]
fixed for 1.0.6
