### ISSUE TITLE
Janky Armors

### ISSUE THREAD

**Issue by NeXusGunCaster** [zhongjiedong/Tsukiro#143]
### What happened?

All yohra 2B armors and  Celes rogue cuirass cause the body of both the player and npc to become all disfigured and janky.

### Modlist version

Tsukiro ver. 1.0.5

**Comment by zhongjiedong** [comment]
Did you use any of these sliders in racemenu

UNPB Chapi - For it can be imitated by other sliders
UNPB Oppai v1 - For it's so similar to UNPB Oppai v3.2 and it can be imitated by other sliders
UNPF Series - For these sliders are ugly as hell.
CNHF + CNHF bonus - It's not used. Not popular
Venus - It's not used. Not popular
Seraphim - For it can be imitated by other sliders
UNPK Bonus - For it can be imitated by other sliders
UNPSH - For it can be imitated by other sliders
DreamGirl - For it can be imitated by other sliders

**Comment by zhongjiedong** [comment]
fixed for 1.0.6

**Comment by NeXusGunCaster** [comment]
Nice, love this modlist its the only way I play Skyrim.

Also nice to meet you. <3
