### ISSUE TITLE
vampire lord bug

### ISSUE THREAD

**Issue by NeartLawt7** [zhongjiedong/Tsukiro#144]
### What happened?

vampire lord will made human form dodge become stuck , 1 u vampire power awaking does not matter who turn u into vampire when u into human form u dodge will be stuck u cant use dodge anymore when u presss dodge button it will be u charater stuck in a very funny pose cant move , also the race manu cant be use anymore when vampire power awaking if u turn on race manu it will crash auto quick game , the race will be : player race , not vampire nord race 
### Modlist version

v2.4.4

**Comment by zhongjiedong** [comment]
not unmodified list

**Comment by NeartLawt7** [comment]
?
