### ISSUE TITLE
new save game for Start ?

### ISSUE THREAD

**Issue by iBeardBros** [zhongjiedong/Tsukiro#15]
![vXK3IEe](https://user-images.githubusercontent.com/86147835/123612611-61ae8800-d80b-11eb-9d08-07c4b903922b.jpeg)
So the old savegame require some addons that u remove from modlist...

**Comment by zhongjiedong** [comment]
if you're updating from a save older than 0.6 then yes it's not compatible

**Comment by iBeardBros** [comment]
so where i get a new save ?

**Comment by zhongjiedong** [comment]
same place you always got it, its named START when you press load.

If you cant see it you might have the bug where MO2 isnt looking in your profile for saves and you need to copy the START save to the one in the your documents\my games\skyrim special edition folder
