### ISSUE TITLE
Unable to install Tsukiro

### ISSUE THREAD

**Issue by Ranezz** [zhongjiedong/Tsukiro#151]
Tsukiro failed to install some mods from nexus. Tried downloading it manually but some mods are deleted for e.g. [ColdSun's Creations - 20 High Poly NPC Replacers - DELETED](https://www.nexusmods.com/skyrimspecialedition/mods/55701) .

**Comment by zhongjiedong** [comment]
please post the wabbajack log here

**Comment by Ranezz** [comment]
Thanks for the fix, tried redownloading thru wabbajack the next day, worked without any issue. Thanks again.
