### ISSUE TITLE
Installation does not finish

### ISSUE THREAD

**Issue by Wabbajohn** [zhongjiedong/Tsukiro#154]
### What happened?

Hi, I tried installing Tsukiro. But after seemingly downloading all the mods, Tsukiro does not want to be installed.

Could you help me? I have been so looking forward to playing this version of Skyrim.

[error log Tsukiro.txt](https://github.com/zhongjiedong/Tsukiro/files/9561211/error.log.Tsukiro.txt)

### Modlist version

1.0.6

**Comment by zhongjiedong** [comment]
delete F:\Wabbajack\downloaded_mod_lists\wj-featured_@@_tsukiro.wabbajack and try again

**Comment by Wabbajohn** [comment]
I swear, I had tried that before two or three times. But after you have suggested it, it suddenly worked. Magic!

Thanks a lot!
