### ISSUE TITLE
Paragon clothing bug

### ISSUE THREAD

**Issue by c-mart-88** [zhongjiedong/Tsukiro#156]
### What happened?

Paragon sparrow pants are invisible and Paragon sparrow top makes the players and NPC's body invisible.
![Screenshot_61](https://user-images.githubusercontent.com/111605334/192912551-be2df195-d5cc-4343-b2be-99f900f19f7e.png)

### Modlist version

1.0.6

**Comment by c-mart-88** [comment]
I did not use console commands to spawn clothes, they were on a robber
![Screenshot_60](https://user-images.githubusercontent.com/111605334/192913344-7b15f2a5-b35b-4f71-9030-e916b8842674.png)

**Comment by zhongjiedong** [comment]
not a bug, pieces were obtained via cheating
