### ISSUE TITLE
Unable to download though WABBAJACK.

### ISSUE THREAD

**Issue by richtrains** [zhongjiedong/Tsukiro#159]
### What happened?

A bug happened!
Failed to Download!

### Modlist version

Could not find another way to contact Anyone to help resolve the issue.

A copy of the log file 
[Wabbajack.current.log](https://github.com/zhongjiedong/Tsukiro/files/10252425/Wabbajack.current.log)

**Comment by zhongjiedong** [comment]
try again if u cant do it then download manually using one of the nexus mirrors

**Comment by richtrains** [comment]
how do i do that i downloaded it from nexus mods and it won't install or unzip

**Comment by richtrains** [comment]
from what I can figure out there is something wrong with the mod even when I try to install it with the mod manager it's only 600mb when on the site it supposed to be 5.4GB

**Comment by zhongjiedong** [comment]
try different servers

**Comment by enipid** [comment]
I'm having the same problem.. could you please link the download page for EVW?

**Comment by zhongjiedong** [comment]
when you click on manual download pick one of these servers: 

https://images-ext-1.discordapp.net/external/2nJHlid9tGPqOC0oN9Bj57yYZLo82yVDzg8fZA4T6Rc/https/i.imgur.com/zN6Lini.png

**Comment by richtrains** [comment]
thanks for the help it looks to be working

**Comment by enipid** [comment]
> when you click on manual download pick one of these servers:
> 
> https://images-ext-1.discordapp.net/external/2nJHlid9tGPqOC0oN9Bj57yYZLo82yVDzg8fZA4T6Rc/https/i.imgur.com/zN6Lini.png

Hey, sorry i'm new to modding and I'm not sure how to get to the download site to begin with. I tried searching it on the Nexus but it doesnt pop up. Could I have some help with that?

**Comment by richtrains** [comment]
https://www.nexusmods.com/skyrimspecialedition/mods/23006?tab=files

**Comment by richtrains** [comment]
that should be the mod

**Comment by enipid** [comment]
tysm!!

**Comment by richtrains** [comment]
no problem took me forever to find it
