### ISSUE TITLE
Unable to install. 

### ISSUE THREAD

**Issue by Ajhero91** [zhongjiedong/Tsukiro#160]
### What happened?

A bug happened! was unable to download the 5 gig evw 7.3 but i saw in a previous post that i could be manually downloaded which i did. i put it into the downloads folder associated with the modlist but it is still trying to download it from nexus. any idea how to fix this?

thanks

### Modlist version

wabbajack 3.0.4.1

**Comment by IamUSER** [comment]
It's sort of answered in the closed issue from 3 days ago, but you need to download the file from a Premium Nexus server. The default download server for Enemy Variations Wenches 7.3 is serving a lite version.

**Comment by IamUSER** [comment]
Similar problem. Closed and reopened wabbajack and it ran.

**Comment by daz001** [comment]
Make sure you're downloading it from a mirror on nexus - as the default CDN contains the bugged one which is 615mb~, and make sure you're downloading 7.3 from the 'old files' section and not 7.3.1

**Comment by Ajhero91** [comment]
so i finally got around to reinstalling this modpack after i got pissed and uninstalled the download folder. now i was able to download the evw mod but now i cant finish installation due to needing the more nasty creatures 8a mod. the author has the 8b mod published with no backlog of the 8a version... such frustration.
