### ISSUE TITLE
Can't Install / Broken on Wabbajack

### ISSUE THREAD

**Issue by CosmicCharlie88** [zhongjiedong/Tsukiro#163]
### What happened?

GS_SLAL SE 27 11.7z   AND   GS_SLAL SE Creatures 20 02.7z   ....are both missing versions on SexLab.
There are newer/older versions but Wabbajack won't accept. 
I even renamed the 7zip files and manually placed them....still won't work. Please fix or take the pack off of Wabbajack.

### Modlist version

Whatever is currently up on Wabbajack 12/26/2022

**Comment by loeweni** [comment]
you can find the files on gunslicers patreon here https://www.patreon.com/Gunslicer/posts

**Comment by BasedCigar** [comment]
After manually downloading both files from patreon and placing them in the mods download folder Wabbajack is still prompting me to download 'GS_SLAL SE Creatures 20 02.7z' from SexLab.

**Comment by liammichaele** [comment]
> After manually downloading both files from patreon and placing them in the mods download folder Wabbajack is still prompting me to download 'GS_SLAL SE Creatures 20 02.7z' from SexLab.

I'm having the same issue, managed to find the download but wabba doesn't it seem to recognise GS_SLAL SE Creatures 20 02.7z from Patreon

**Comment by atmawander** [comment]
Hello everyone, I'm having the same issue waba is not recognising the files.

**Comment by tungns0695** [comment]
i also face the same issuse

**Comment by BasedCigar** [comment]
The tl;dr is that the patreon version is not the same as the one that was previously on LoversLab. 

Modlist author seems to be aware of this and we basically have to wait for him to update the list unless you can somehow find the original version that was on LL.

**Comment by yunacchi** [comment]
Contents of `GS_SLAL SE Creatures 20 02.7z` differ between LL's removed version and Patreon's version, for some reason.

If you know how to edit a modlist, you could still get [`GS_SLAL SE Creatures 20 02.7z`](https://www.patreon.com/posts/slal-creatures-62822632) and [`GS_SLAL SE 27 11.7z`](https://www.patreon.com/posts/slal-28-11-75208554) into WJ's downloads, with the following replacements:

- `3KSmOKYrHH8=` => `HX7/e0OgNtU=`
- `"Name":"GS_SLAL SE Creatures 20 02.7z","Size":13484008` => `"Name":"GS_SLAL SE Creatures 20 02.7z","Size":13484916`
- `FNIS_GS_SLAL_Creatures_Behavior.hkx"],"Hash":"9WrKZJ83R3M=","Size":176800` => `FNIS_GS_SLAL_Creatures_Behavior.hkx"],"Hash":"U8t6jMiTNZs=","Size":176168`
- `FNIS_GS_SLAL_Creatures_List.txt"],"Hash":"rxZ8JK3tndE=","Size":10858` => `FNIS_GS_SLAL_Creatures_List.txt"],"Hash":"9oU2xNPbswM=","Size":10857`


This is obviously *completely unsupported*, and I would bet that the game crashes when loading the relevant Creatures animation (considering FNIS isn't up to date). But installation and new characters work fine after that.

If you don't know or have to ask, wait for a proper update to the modlist.
