### ISSUE TITLE
No "START" Save

### ISSUE THREAD

**Issue by ItzMaddMaxx** [zhongjiedong/Tsukiro#165]
### What happened?

Launched Tsukiro and didn't see the "Start" save.  How would I go about finding or installing it?

### Modlist version

1.2.1

**Comment by zhongjiedong** [comment]
Sorry forgot to rename it, should just be the first save 001 Adventurer

**Comment by ItzMaddMaxx** [comment]
Oh ok.  I just found it strange because I was just spawning in Helgen as a character I didn't create and I'm not able to look around or jump.  I thought it just wasn't the save.

**Comment by ItzMaddMaxx** [comment]
I got everything working.  Thanks for the clarification.
