### ISSUE TITLE
Change FOV

### ISSUE THREAD

**Issue by reselecta** [zhongjiedong/Tsukiro#166]
### What happened?

Is there anyway to change the 1st person FOV? I tried to set in the console but it defaults to 80, edited the Beth.ini but as it only works on new saves it doesn't work. Additional mods and editing the skyrim ini's also don't work

Love the modlist irregardless just prefer 1st person over 3rd where possible

### Modlist version

1.2.1

**Comment by zhongjiedong** [comment]
shift+home to open improved camera options

**Comment by reselecta** [comment]
Got it, missed that menu when i was going through it all

Many thanks
