### ISSUE TITLE
Im Dumby

### ISSUE THREAD

**Issue by JDiddy2004** [zhongjiedong/Tsukiro#168]
### What happened?

A bug happened! And its my brain.  I simply tried to follow the thing step by step but not only did that break for me. once at the modmanager bit I  just fail. Im essentially a boomer in modding terms.   😢 
![image_2023-01-17_041100296](https://user-images.githubusercontent.com/122873676/212870541-e516c1b7-00b5-4b1a-a7d2-c6b36fb9788a.png)

### Modlist version

Newest On Wabbajack?

**Comment by JDiddy2004** [comment]
> ### What happened?
> A bug happened! And its my brain. I simply tried to follow the thing step by step but not only did that break for me. once at the modmanager bit I just fail. Im essentially a boomer in modding terms. 😢 ![image_2023-01-17_041100296](https://user-images.githubusercontent.com/122873676/212870541-e516c1b7-00b5-4b1a-a7d2-c6b36fb9788a.png)
> 
> ### Modlist version
> Newest On Wabbajack?

Also at the step just before its simply not there
![image_2023-01-17_041312226](https://user-images.githubusercontent.com/122873676/212871035-36a9283a-4930-4bf2-b478-7d27c19c8486.png)
The compatibility tab isnt there.

**Comment by zhongjiedong** [comment]
you need to open the mod organizer in the tsukiro install folder not the one you've installed yourself
