### ISSUE TITLE
Save File didnt get me through a racemenu nor gear reload options like in the ss

### ISSUE THREAD

**Issue by octoberz3120** [zhongjiedong/Tsukiro#169]
### What happened?

I finsihed my install, run the tsukiro, load the save but here is just a naked lady on a cliff, i can walk. cant sprint, can't jump
even the camera stays on shoulder cam/
![Screenshot 2023-01-22 121432](https://user-images.githubusercontent.com/123146825/213901714-3d84526a-3810-4625-8d90-2d6ee1961c7f.png)

### Modlist version

latest. as of this bug reporting.

**Comment by Bolo1Hundo** [comment]
Same

**Comment by zhongjiedong** [comment]
press enter
