### ISSUE TITLE
Bow-draw cancels, line-of-fight conflict?

### ISSUE THREAD

**Issue by sigmaD91** [zhongjiedong/Tsukiro#17]
I am playing Tsukiro modpack clean, without any additional mods. Started today and really enjoying it so far!

Just encountered one issue that I have no idea how to resolve...

When I draw the bow to aim down on an enemy, if the enemy is in line of sight to my PC, the bow draw cancels almost immediately (as if the mouse button is released or re-clicked) and the arrow simply fires automatically. This happens regardless of whether I face up or down, simply positioning the crosshair along the pitch of any vertical line from the enemy position triggers this, but ONLY if the enemy is in the PC line-of-sight. I know these details, because I am playing as Bosmer with "Wild Senses". This happens regardless of whether I am sneaking or not, regardless of fpv or tpv, and regardless of whether the enemy has seen me or not. I have tested using a different mouse as well, to rule out a hardware malfunction, so I think this may have something to do with a PC line-of-sight trigger from another mod... which one, however, I have no clue.

Please let me know if there is an easy solution.

Thanks again for an amazing modpack!
Kind Regards

**Comment by sigmaD91** [comment]
UPDATE: I have discovered that this trigger occurs ONLY with M2 button... so whatever is doing this is triggered by holding in M2. This also effects shield and weapon. The shield tends to "jitter" in and out of position when on this line of sight. The weapon cancels the power attack and doubles up on the normal attack. Switching the M1/M2 function solves the issue with the bow, but then creates a new issue for bow-bash and for using a shield in close combat.

So the question is what player line-of-sight trigger operates with M2, and how do I disable this?

**Comment by zhongjiedong** [comment]
hmm can u try disabling worldspace crosshair in the smoothcam MCM and let me know how that works

**Comment by sigmaD91** [comment]
Disabling worldspace crosshair makes no difference, unfortunately.

Also, note when I hold in M2 to draw the bow outside of line-of-sight, even if I then move around to aim, whenever I make the line of sight to start aiming (while still holding in M2 to keep drawn), the bow fires off automatically the moment that vertical line is breached... 

I've scoured the MCM for any kind of trigger... I tried disabling arousal lineofsight triggers... nothing works... whatever is assigned to M2 for some reason is interrupted ONLY when that line of sight is breached, almost like the weapon/shield has been assigned to "auto-attack/auto-trigger" on M2... it's so weird.

**Comment by zhongjiedong** [comment]
when you say "line of sight" you mean the prediction arc? 

Unfortunately I cannot reproduce this and it's the first time anybody has ever reported such an issue.
