### ISSUE TITLE
Sound issues

### ISSUE THREAD

**Issue by Zhaolute** [zhongjiedong/Tsukiro#170]
### What happened?

For some reason, I can't hear attack sounds from melee weapons and fists. Even the horse galloping is very wonky and can only be heard once every 8 seconds. I'm not sure if it's a faulty install or if some mod is overwriting the sounds incorrectly. Is it because I'm playing a male character? I noticed that everyone that has uploaded gameplay of this modpack only plays female characters.

### Modlist version

Latest one.

**Comment by zhongjiedong** [comment]
unlikely anything to do with the modlist, plenty of people play male characters without reporting this issue. This may help:

https://www.nexusmods.com/skyrimspecialedition/mods/71567/

**Comment by Zhaolute** [comment]
You're a genius. Thank you so much. I never would have solved this issue in a thousand years.
