### ISSUE TITLE
Wabbajack download fails on TRX SOS Male Bodyslide SMP

### ISSUE THREAD

**Issue by ThatWeirdGuyWithaWeirdHat** [zhongjiedong/Tsukiro#171]
### What happened?

The downloader fails when trying to download TRX SOS Male Bodyslide SMP (https://www.loverslab.com/files/file/25328-trx-sos-male-bodyslide-smp/). I attempted to rename the downloaded file straight from the site and put it in my download folder, however Wabbajack deletes the file and errors out anyway.

[Wabbajack.log](https://github.com/zhongjiedong/Tsukiro/files/10564135/Wabbajack.log)

### Modlist version

2.1 Beta

**Comment by zhongjiedong** [comment]
fixed in 2.1.1
