### ISSUE TITLE
Can't install Tsukiro

### ISSUE THREAD

**Issue by Crystyanyan** [zhongjiedong/Tsukiro#173]
Wabbajack keep giving me errors on random files that the requested operation requires elevation. I downloaded everything needed and i already went through some troubleshooting. Since the discord server doesn't seem to be able to help out right now i'm trying over here.

**Comment by zhongjiedong** [comment]
post the log

**Comment by Crystyanyan** [comment]
[Wabbajack.current.log](https://github.com/zhongjiedong/Tsukiro/files/10701633/Wabbajack.current.log)

**Comment by Crystyanyan** [comment]
If it helps i can try and post what i already tried to do

**Comment by zhongjiedong** [comment]
you need to run the main wabbajack app dont double click the tsukiro.wabbajack you downloaded

**Comment by Crystyanyan** [comment]
I am running from the main wabbajack.exe

**Comment by Crystyanyan** [comment]
I never even considered running the tsukiro.wabbajack

**Comment by Crystyanyan** [comment]
If it clears something up i am trying to extract and install on an external SSD. Would that help?

**Comment by zhongjiedong** [comment]
we do not support anything on external drives, moving several hundred gigabytes of data across USB is unreliable.

**Comment by Crystyanyan** [comment]
Don't close the issue without even listening. I am not saying that i am transferring data from internal to external. Both the installation,archives and extraction is done on the SSD.

**Comment by zhongjiedong** [comment]
You are not entitled to my time, unless you have your entire OS installed on the external drive, wabbajack has to move files to and from it to process and hash. Get a proper drive and I can continue to help you.

**Comment by Crystyanyan** [comment]
I was just saying that its kind of rude to close it. No i am not entitled to your time,you are right,so thanks for the info. This was a much better explanation. Have a nice day

**Comment by Crystyanyan** [comment]
Since i don't want to start a new topic i will say here that i was able to finish dealing with this. My only issue is that i thought i was having some bugs from a previous version so i deleted the start save. Is that saved anywhere so that i can find it and download it? I would appreciate it

**Comment by zhongjiedong** [comment]
rerunning the install will restore the save
