### ISSUE TITLE
Program Bloat

### ISSUE THREAD

**Issue by nyourcomp** [zhongjiedong/Tsukiro#174]
### What happened?

Seems like a pretty good set up for the most part. Nice complement of mods, and even though it took be nearly 2 days to download all the mods for it, it seemed to install fine (only hit 2 failures due to some SL mods which i DLed and added manually).  But the thing is so over whelmingly bloated with mods it doesnt seem to function correctly.  I suppose if you have a NASA grade computer it might but who the hell can afford one of those things. 

The issue I had really is that Steam VR kept locking up and having errors, and after about 10 attempts it finally loads to a point but I cannot get past the creation screen let alone customize a character.  the framerate is somewhere in the neighborhood of .00000001.  mind you, I followed every detail in the description for the mod installer to the letter save for any adjustments to the headset.  And Im here to tell you that was no small task.  As much as I appreciate the fact that people like this creator go thru the effort to make these thing and the mods themselves, (which most of them are amazing) I cannot pass the chance to point out that those of us who do not make the mods and installers are clearly not nearly as well versed in the implimentation of them as you are, cause if we were we would be among the authors.  Additionally, not everyone can afford one of those monster computers y'all use. 

 All Im asking for here is 1: try to minimize the bloat (or maybe a little word on how we can check off some of the mods in MO2) or even make a light version which can probably be done by you over 1 cup of coffee, and 2: maybe a little more detail when instructing us on how to make all those adjustments that seem so often neccessary.  I had to do numerous google searches to find most of the things I had to change.  there were something inside the headset that i simply could find.

OH, and for anyone else who may read this for information purpose.  if you try to play around with the mod list by trying to disable some to clear it up, be damn careful.  I managed to mess my installation up and to save on the down load time (2 days) i called my self pulling the archived files from the "download" file out of that folder and storing it so that once i got the redo started up i could just shift those files back in and not have to DL them again.  Uh Yeah, that shit didnt work.  this program searched for and found that file that was stored in not only a different file named nothing remotely like it, but also on an entirely seperate drive! and deleted the damn thing in the bat of an eye.  2 more f*cking days of my life I'll never get back!

Headset: Quest 2
laptop: Asus Model FX706H (with the i5)

### Modlist version

Not sure of the version, but DLed it on 2/8/23 so Id say the newest one?

**Comment by zhongjiedong** [comment]
er are you lost? This isn't a VR modlist
