### ISSUE TITLE
Weird letters in Eltrys Note

### ISSUE THREAD

**Issue by Hansamuna** [zhongjiedong/Tsukiro#18]
I get weird letters in the note Eltrys give after you enter Markarth and witness the murder. just updated and started a new game. For now it is the only book/note I found with this bug. Also when you start a new game with the save 62b I still get a missing mod error (scribesofskyrim).
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2021 07 02 - 18 22 27 68](https://user-images.githubusercontent.com/86857975/124334190-57222480-db64-11eb-95d4-74ba32803b92.png)

**Comment by zhongjiedong** [comment]
Thanks for report, this was as a result of removing scribes, please keep reporting any broken books/notes I will have missed some

**Comment by Hansamuna** [comment]
> Thanks for report, this was as a result of removing scribes, please keep reporting any broken books/notes I will have missed some

Seems like another note in the same quest have the bug. This time it is Weylin Note. Its the Forsworn Conspiracy quest.

**Comment by Hansamuna** [comment]
Same for the notes in the quest No One Escapes Cydhna Mine. (Note from Madanach)

**Comment by Hansamuna** [comment]
Book : Boethiah's Proving

**Comment by zhongjiedong** [comment]
Ok update to latest version, all the books should be sorted now :)

**Comment by Hansamuna** [comment]
Just updated. Good job this is fixed 👍
