### ISSUE TITLE
trying to install keeps failing

### ISSUE THREAD

**Issue by kev9534** [zhongjiedong/Tsukiro#19]
install keeps failing right at the end looking for GS_SLAL 07 03.7z cant go any further have tried and tried same message all the time that its failed don't know what to do ??? any help Thanks
![Screenshot (2)](https://user-images.githubusercontent.com/86980835/124507889-ae273400-ddc6-11eb-83c8-505fc0b292f5.png)

**Comment by zhongjiedong** [comment]
Should be fixed with last update

**Comment by kev9534** [comment]
still failing what do i  do

**Comment by zhongjiedong** [comment]
delete the wabbajack file in downloaded_modlists and try again
