### ISSUE TITLE
Key not valid for use in specified state. Please help.

### ISSUE THREAD

**Issue by Falloflast** [zhongjiedong/Tsukiro#20]
Hello, I've got a couple of problems when try to download tsukiro. First is white screen when I try to log into sexlab account, it happens when I click "continue as". I saw people who had the same thing but didn't find a way to fix it. And second problem which is more important because I can't even find people who encountered it. "Key not valid for use in specified state", as I understood it's related to nexus api key. I'd really love to try out tsukiro and don't know how to fix these problems.

[Wabbajack.current.log](https://github.com/zhongjiedong/Tsukiro/files/6767942/Wabbajack.current.log)

**Comment by csirke128** [comment]
For white screen issue, try upgrading windows:
https://github.com/wabbajack-tools/wabbajack/issues/1515

Had the same issue, upgraded from 1909 to 20H2 and after that it worked.

**Comment by zhongjiedong** [comment]
> 
> 
> Hello, I've got a couple of problems when try to download tsukiro. First is white screen when I try to log into sexlab account, it happens when I click "continue as". I saw people who had the same thing but didn't find a way to fix it. And second problem which is more important because I can't even find people who encountered it. "Key not valid for use in specified state", as I understood it's related to nexus api key. I'd really love to try out tsukiro and don't know how to fix these problems.
> 
> [Wabbajack.current.log](https://github.com/zhongjiedong/Tsukiro/files/6767942/Wabbajack.current.log)

Hello can you upload the log in a zip folder, this is not downloadable

**Comment by Falloflast** [comment]
Hello, I've asked about it in wabbajack discord channel and they said that it's related to the sexlab log in problem. I've updated wabbajack and windows as well, but nothing changed. They said that it's because of windows version. I've put log in a zip folder (this is and old one before updates but nothing changed.). I assume, it's not your problem it's something wrong with wabbajack and windows updates.
[Wabbajack.current.zip](https://github.com/zhongjiedong/Tsukiro/files/6779792/Wabbajack.current.zip)

**Comment by zhongjiedong** [comment]
can u make sure u have this installed https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by Falloflast** [comment]
Yes, I've read the instruction. I may try to reinstall.

**Comment by Falloflast** [comment]
I've tried to download another swf mod list and it worked. So the problem is LL log in.

**Comment by zhongjiedong** [comment]
should be fixed by updating windows. Can you confirm?
