### ISSUE TITLE
Bug:  Sleeping while sneaking causes player to be stuck crouching

### ISSUE THREAD

**Issue by Corbillion** [zhongjiedong/Tsukiro#21]
Hope you can replicate.
After sleeping while sneaking character will become stuck crouching.  Pressing sneak will not toggle this, tired other things like jumping, rolling etc and these things work but do not rectify the problem.  Have to reload a save to fix.

**Comment by zhongjiedong** [comment]
sit on a chair or use a crafting station to fix. Will look into a more permanent solution

**Comment by zhongjiedong** [comment]
This will be fixed in next update.
