### ISSUE TITLE
Unable to download a few mods

### ISSUE THREAD

**Issue by mall3333** [zhongjiedong/Tsukiro#23]
I was unable to download these mods:

GS_SLAL SE 07 03.7z 
Marvelous Mirabelle 1.01
MoreNastyCritters_v12_5SE
Nether's Follower Framework - Universal Installer
Nether's Karliah - Universal Installer (LE or SSE)

Maybe they've been updated/removed? Or maybe i did something wrong?

**Comment by zhongjiedong** [comment]
delete the tsukiro.wabbajack file and the meta and redownload from UI
