### ISSUE TITLE
cant download [COCO] Pinup Cheongsam [SE]

### ISSUE THREAD

**Issue by CDRShepard96** [zhongjiedong/Tsukiro#24]
![notepad++_2021-07-08_04-12-46](https://user-images.githubusercontent.com/71482465/124896321-f26f2b80-dfa2-11eb-9c69-0ad97500f5b3.png)

**Comment by zhongjiedong** [comment]
https://drive.google.com/file/d/1L75e_NR6rCrCXK16icDmPOGNcRQSfZuR/view


download manually, place the file in the folder with your other downloads

**Comment by CDRShepard96** [comment]
thank you :)
