### ISSUE TITLE
Game Crashes On Main Menu

### ISSUE THREAD

**Issue by romisuser** [zhongjiedong/Tsukiro#25]
Title.

I downloaded Skse from the official website and used that one because MO2 wouldnt start the skse that was included in the "Game Folder Files" because it was corrupted and unreadable.

**Comment by zhongjiedong** [comment]
and it stil crashes?

**Comment by romisuser2** [comment]
Yes, the game wouldn't even start with previous skse loader but now it crashes at the main menu. I don't know if its because of different skse or something else.

**Comment by zhongjiedong** [comment]
can you post a picture of your skyrim folder with the path visible and as much files too

**Comment by romisuser2** [comment]
![Trouble shoot](https://user-images.githubusercontent.com/87232860/125182480-4a2ec080-e249-11eb-9853-01e5736373cd.PNG)
This is inside the skyrim directory.
![Trouble shoot 2](https://user-images.githubusercontent.com/87232860/125182492-5ca8fa00-e249-11eb-9256-f3229033e53c.PNG)
This is in the Tsukiro folder.
![trouble shoot 3](https://user-images.githubusercontent.com/87232860/125182496-67fc2580-e249-11eb-8a60-dcd5e495a01c.PNG)
This is in a different skyrim folder (idk what it is or how it got there) which has files for the skse.
![trouble shoot 4](https://user-images.githubusercontent.com/87232860/125182516-9f6ad200-e249-11eb-8644-701717cb0f2f.PNG)
This is the last couple of lines from what looks to be a log.


I didn't know what files specifically you were referencing so I got whatever might be helpful.

**Comment by zhongjiedong** [comment]
can u check if theres any crash logs in the overwrite in mo2

**Comment by romisuser2** [comment]
[Crash_2021_7_11_13-59-7.txt](https://github.com/zhongjiedong/Tsukiro/files/6796856/Crash_2021_7_11_13-59-7.txt)
Is this what you are referring to?

**Comment by zhongjiedong** [comment]
yes, you might need to increase your  pagefile, this appears to be a memory crash. I suggest 20GB pagefile

**Comment by romisuser2** [comment]
After increasing my pagefile to 20GB I still crash at the main menu.
Here is the most recent log:
[Crash_2021_7_12_12-37-13.txt](https://github.com/zhongjiedong/Tsukiro/files/6798451/Crash_2021_7_12_12-37-13.txt)

**Comment by zhongjiedong** [comment]
shouldnt be since that's the same way I have it setup. I would suggest deleting your entire skyrim folder and also the folder in documents\my games\ and reinstall skyrim and see if you continue to have issues

**Comment by romisuser2** [comment]
A deleted the skyrim se folders, changed pagefile from 20GB to 60GB, changed skyrim graphics from to ultra, and replaced the skse.exe and the game still crashes at main menu.
[Crash_2021_7_12_20-51-16.txt](https://github.com/zhongjiedong/Tsukiro/files/6801088/Crash_2021_7_12_20-51-16.txt)

**Comment by zhongjiedong** [comment]
the crash log shows only 5 plugins being loaded. You must have some kind of antivirus that's breaking MO2 when it's launching skyrim

**Comment by romisuser2** [comment]
I had avast installed, deleted it, game still crashes, still only 5 plugins load.
I didn't have a premium nexus acc so i installed the mods manually, maybe i installed the mods wrong or something. Maybe i dont have enough storage space, I only have 4.6 gb left on my D: drive.

**Comment by romisuser2** [comment]
Ive disabled all mods and started enabling them in small batches to see if I can find the issue. Some mods when I enable them by themselves with no other mods work fine. Sometimes when multiple (but not all) mods are enabled skyrim infinitely loads the main menu (but doesn't crash). It also seems there is a problem with some of the mods dll files as I get the following error when launching the game with those mods (the following example is from Better Power Attack Directional Control - SSE):

MaxsuPowerAttackControl.dll

REL/Relocation.h(653): failed to open file

**Comment by zhongjiedong** [comment]
u probably dont have enough disk space for it to finish the install/

Do u actually see the "install complete" screen?

**Comment by romisuser2** [comment]
Yep, it warns me that i have low space remaining but it says installation complete.

**Comment by zhongjiedong** [comment]
i would try and clear some space and try again it's saying it will stop at 4.7 and u only have 4.7

**Comment by Corbillion** [comment]
I have my download 
directory for Tsukiro on a different drive, saves a lot of space so I can have 100GB page file, maybe try that?

![image](https://user-images.githubusercontent.com/49664721/125443292-5b16d3fc-9d08-4dab-b3d4-f2a54e2d2c72.png)

**Comment by romisuser2** [comment]
> i would try and clear some space and try again it's saying it will stop at 4.7 and u only have 4.7

Cleared up 64Gb and ran the installer again, same issue

**Comment by romisuser2** [comment]
> I have my download
> directory for Tsukiro on a different drive, saves a lot of space so I can have 100GB page file, maybe try that?
> 
> ![image](https://user-images.githubusercontent.com/49664721/125443292-5b16d3fc-9d08-4dab-b3d4-f2a54e2d2c72.png)

I don't think I have the space to split up my drives like that, there would still be the issue of low space.

**Comment by zhongjiedong** [comment]
Did you completely remove avast or just disable? Do you have any other kind of antivirus like malwarebytes etc?

**Comment by romisuser2** [comment]
I completely removed avast, no other anti virus installed

**Comment by romisuser2** [comment]
Just increased C: drive pageflie to 60Gb and D: drive to 80Gb, gonna see if that works.

**Comment by zhongjiedong** [comment]
have u got a fully updated win10?

**Comment by romisuser2** [comment]
Yes

**Comment by zhongjiedong** [comment]
Can you launch skyrim from steam and get ingame without crashing?

**Comment by romisuser2** [comment]
Vannila launch loads main menu just fine and I can start a new game with no issues

**Comment by zhongjiedong** [comment]
and the plugins in MO2, they're all ticked?

**Comment by romisuser2** [comment]
Yep, all ticked

**Comment by romisuser2** [comment]
> Ive disabled all mods and started enabling them in small batches to see if I can find the issue. Some mods when I enable them by themselves with no other mods work fine. Sometimes when multiple (but not all) mods are enabled skyrim infinitely loads the main menu (but doesn't crash). It also seems there is a problem with some of the mods dll files as I get the following error when launching the game with those mods (the following example is from Better Power Attack Directional Control - SSE):
> 
> ![error](https://user-images.githubusercontent.com/87232860/125293026-fbbf1600-e35d-11eb-8be6-fc480e3019af.PNG)

I found this issue when testing the mods in batches, is this normal?

**Comment by zhongjiedong** [comment]
its not a mod causing this. If you are disabling mods then they will be in the wrong order when re-enabled. Please reinstall the list

**Comment by romisuser2** [comment]
I'd already reinstalled the mods after this.

**Comment by zhongjiedong** [comment]
i mean reinstall the list.

**Comment by zhongjiedong** [comment]
no just run wabbajack again using the overwrite installation option

**Comment by romisuser2** [comment]
Did that, still crashed.

I mentioned earlier that the skse files that came in the "Game folder files" didn't work and I had to use different ones, have you or anyone else had the same issue?

**Comment by zhongjiedong** [comment]
no, you are the only one with this problem. What happens when you launch the game from MO2?

**Comment by zhongjiedong** [comment]
what is your installation location for the modlist?

**Comment by romisuser2** [comment]
if i replace just the skse executable then I get another error concerning the skse .dlls but MO2 launches the game

**Comment by zhongjiedong** [comment]
put the skse exe back and see if it launches if u just double click it

**Comment by romisuser2** [comment]
This is the error i get for that:

![Capture](https://user-images.githubusercontent.com/87232860/125463507-cd667384-7c98-4961-98a2-3f252caf2b56.PNG)

**Comment by zhongjiedong** [comment]
what error do u get if you replace it and double click it?

**Comment by romisuser2** [comment]
![Capture](https://user-images.githubusercontent.com/87232860/125464206-4014c37b-88ec-40aa-8007-dda75f951f4c.PNG)
I get this but the skse launches eventually.

**Comment by romisuser2** [comment]
replacing the .dll mentioned in the error gives the other .dll the same error

**Comment by zhongjiedong** [comment]
u got something very wrong with ur pc i think. May need to reinstall windows

**Comment by romisuser2** [comment]
I'll try some more stuff and get back to you.

**Comment by zhongjiedong** [comment]
it may be these files: https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

**Comment by romisuser2** [comment]
OK so I managed to get the ORGINAL skse files from game folder files to work no corruption or unreadable errors.


The game still crashes at main menu.

**Comment by zhongjiedong** [comment]
ok but did u install the files in that link, you need x64 version

**Comment by romisuser2** [comment]
Yes installed vc_redist.x64.exe, game still crashes

**Comment by zhongjiedong** [comment]
are there any warnings in MO2 in the top right?
![2021-07-13 15_33_26-Skyrim Special Edition – Mod Organizer v2 4 2 (zhongjiedong_)](https://user-images.githubusercontent.com/20669755/125470776-73abf8fe-4643-47bf-b4c8-39d9ebefaa55.png)

**Comment by romisuser2** [comment]
Only warning is "There are files in your overwrite directory"

**Comment by romisuser2** [comment]
Downloading the updated Tsukiro, hopefully that does some good.
,

**Comment by Corbillion** [comment]
Can you post the specs of your machine @romisuser2?   I have a feeling your machine is not capable of running this modlist.  It might be ok for vanilla Skyrim but modlists like these require a lot more grunt.

**Comment by romisuser2** [comment]
AMD Ryzen 3 3300X 4-Core Processor  3.79 GHz
Nvidia Geforce GTX 970 
Biostar a320mh
8GB Ram
500w 80+ psu

**Comment by Corbillion** [comment]
Might be your ram, mine has 16gb and uses almost all of it.  @zhongjiedong please confirm.

**Comment by romisuser2** [comment]
If it was my ram wouldn't that just cause issues ingame rather launch issues?

**Comment by zhongjiedong** [comment]
probably unable to load everything into RAM and that's why you cant launch the game but dont know for sure

**Comment by romisuser2** [comment]
Im going to delete everything in my Wabbajack\Modlists\Tsukiro folder (excluding the downloads) and reinstall it via Tsukiro.wabbajack. This is probably the last thing I'm going to try and if it doesn't work I guess we can just chalk it up to not having enough RAM.

**Comment by Corbillion** [comment]
Well there are things you can do to reduce the load, don't use ENB for example.  Also can lower resolution scale in the SSEDisplayTweaks.ini file.  Play on medium or low settings is another.

**Comment by Corbillion** [comment]
Maybe slowly reduce the quality and see if it helps, if not then it rules out hardware specs.  What resolution is your monitor?

**Comment by romisuser2** [comment]
HAHAHA, reinstalling worked (I also scaled down to 1280x720 so that might have been it too). Sure, Skyrim used nearly 4GB of memory and my 93% of my total memory was being used at its peak, but hey, it didn't crash.

**Comment by romisuser2** [comment]
@zhongjiedong I think you can now mark this as closed.

**Comment by zhongjiedong** [comment]
yeah i think u just dont have enough RAM. 600 plugins is going to start eating a lot of RAM
