### ISSUE TITLE
random crashes

### ISSUE THREAD

**Issue by CDRShepard96** [zhongjiedong/Tsukiro#28]
randomly crashes to desktop while exploring.

**Comment by CDRShepard96** [comment]
and newest crash log
[Crash_2021_7_12_21-23-19.txt](https://github.com/zhongjiedong/Tsukiro/files/6805462/Crash_2021_7_12_21-23-19.txt)

**Comment by CDRShepard96** [comment]
found location of where it crashes anywhere near hunters rest near falkreath, tried fast traveling there and crashed instantly.

**Comment by zhongjiedong** [comment]
thanks will look into this.

**Comment by Corbillion** [comment]
[Crash_2021_7_13_15-38-19.txt](https://github.com/zhongjiedong/Tsukiro/files/6807723/Crash_2021_7_13_15-38-19.txt)

**Comment by CDRShepard96** [comment]
yep found the place u crashing from called "Anise's Cabin" north side of the river, crashed for me also going near it.

**Comment by CDRShepard96** [comment]
Old Hroldan seems to be a place also, crashed me once, was fine for a bit then crashed me again.

**Comment by Corbillion** [comment]
Cant open my save anymore so gonna wait for next patch before playing again :)

**Comment by Corbillion** [comment]
I did disable the signposts mod, not sure if that is contributing.

**Comment by zhongjiedong** [comment]
if u disable mods then yes your save can fail to load

**Comment by Corbillion** [comment]
well it worked for ages until I went to helgen on wenches quest, I disabled it few days ago

**Comment by CDRShepard96** [comment]
iv tried with and with out it it loads fine for me but location crashes still occur

**Comment by Corbillion** [comment]
do you ever get random CTD Zhong?

**Comment by zhongjiedong** [comment]
yes I've fixed the random CTD, it's due to an NPC mod being updated. It will be live in a few hours

**Comment by Corbillion** [comment]
Awesome thanks mate

**Comment by Corbillion** [comment]
Love your work btw, just not not a fan of the signposts, everything else fits together awesome

**Comment by CDRShepard96** [comment]
i dont mind it but its a pain to try to find the posts XD

**Comment by Corbillion** [comment]
Yeah, if they had some way to mark the location of them on the map Id definately use it

**Comment by CDRShepard96** [comment]
but yeah loving the pack :) iv been trying to lower the lod for things tho, pc isnt quite as good as urs XD

**Comment by Corbillion** [comment]
@zhongjiedong this one might be better mate, he's done some compatibility testing (old hroldan mentioned) and it has an MCM to turn on or off fast travel for those that want to still use it:

https://www.nexusmods.com/skyrimspecialedition/mods/16646

**Comment by CDRShepard96** [comment]
ohh @Corbillion for ur save regarding helgan try load a save thts a few saves back, might have saved in sight of a place tht crahes you

**Comment by Corbillion** [comment]
@CDRShepard96 thanks mate, yeah I considered that, its highly likely too I was save scumming as i got closer and closer so I could test the crash better, can load an older one ok but its not the only place I have been crashing so hoping next patch will be more stable, happy to wait ;)

**Comment by CDRShepard96** [comment]
yep how i found the 2 places, 2 dif saves looking for spots, testing if it was only me or some error.

**Comment by zhongjiedong** [comment]
hmm what is the error in lux?

**Comment by CDRShepard96** [comment]
only when loading a save from 0.71
![SkyrimSE 2021-07-13 07-16-16](https://user-images.githubusercontent.com/71482465/125450181-39b6a47d-be70-4fae-a3d4-e9d18fd5bd5d.png)

**Comment by zhongjiedong** [comment]
oh damn, well it might be a bit darker on 0.72 lol. Will fix later

**Comment by zhongjiedong** [comment]
can run Bethini with medium preset instead of high, might help

**Comment by CDRShepard96** [comment]
ahhh okies i was wondering how to use those files XD thx :)

**Comment by zhongjiedong** [comment]
fixed in 7.2
