### ISSUE TITLE
Random CTD

### ISSUE THREAD

**Issue by Corbillion** [zhongjiedong/Tsukiro#29]
Hi there,

Just had another random CTD, this one does not seem to be easily recreated, was sniping a bandit camp and game exited.  Have attached crash log here, hope you can find the cause.
[Crash_2021_7_17_13-54-33.txt](https://github.com/zhongjiedong/Tsukiro/files/6834112/Crash_2021_7_17_13-54-33.txt)

**Comment by Corbillion** [comment]
Hmm happened again same place
[Crash_2021_7_17_14-3-11.txt](https://github.com/zhongjiedong/Tsukiro/files/6834126/Crash_2021_7_17_14-3-11.txt)

**Comment by CDRShepard96** [comment]
iv had a few also but went back to spot and it was fine, so i havent worried about it so far.

**Comment by CDRShepard96** [comment]
this the latest from me
[Crash_2021_7_17_2-27-32.txt](https://github.com/zhongjiedong/Tsukiro/files/6834357/Crash_2021_7_17_2-27-32.txt)

**Comment by zhongjiedong** [comment]
reboot your PC

@CDRShepard, avoid saving right after handing in or taking quests.

**Comment by Corbillion** [comment]
Another one
[Crash_2021_7_18_11-27-17.txt](https://github.com/zhongjiedong/Tsukiro/files/6835522/Crash_2021_7_18_11-27-17.txt)

**Comment by zhongjiedong** [comment]
is this repeatable?

**Comment by Corbillion** [comment]
will try to repeat

**Comment by Corbillion** [comment]
Seems to be random, just had another when I tried to load my last save after dying.  I play Living Skyrim too and never get these crashes.
[Crash_2021_7_18_11-54-13.txt](https://github.com/zhongjiedong/Tsukiro/files/6835542/Crash_2021_7_18_11-54-13.txt)

**Comment by Corbillion** [comment]
Has anyone else reported crashes or just me and CDRShepard?

**Comment by zhongjiedong** [comment]
how many times are u loading the save and are u dying a lot?

**Comment by Corbillion** [comment]
The same save or different ones?  2 or 3 times would be the most, I don't die that often, mainly die when I get mobbed, no followers at the moment so odds are against me at times.

**Comment by Corbillion** [comment]
Is it ok if I just keep uploading crash logs here?  Maybe there will be something in common in the logs that gives us a clue.

**Comment by zhongjiedong** [comment]
sure but from what ive seen so far there's no pattern

**Comment by Corbillion** [comment]
Yeah same here have been checking myself and checking windows logs but they never seem to add anything useful.

**Comment by CDRShepard96** [comment]
i normaly get ctd when ever i try to leave a building.

**Comment by zhongjiedong** [comment]
are u saving when leaving?

**Comment by CDRShepard96** [comment]
ah i do have save on travel on but never affected me before

**Comment by zhongjiedong** [comment]
if thats been on then you've slowly been bloating your save. Auto saves are off for a reason
