### ISSUE TITLE
Vampirism and racemenu

### ISSUE THREAD

**Issue by skinnyarab** [zhongjiedong/Tsukiro#30]
not really a hyuge issue as fixable with player.setrace, but whenever using racemenu, "vampirism" is kind of lost as harkons court wont recognize and you can no longer feed on humans until you change your race back to vampire via console

-bobbysch

**Comment by zhongjiedong** [comment]
vanilla bug, sometimes happens just set your race to vampire via console

player.setrace xxxRaceVampire where xxx is your base race (Nord, Imperial etc)
