### ISSUE TITLE
BHUNP 3BBB Thief Leather Armor? Who's the author? What's the website? Please Help!

### ISSUE THREAD

**Issue by ringostarsky1500** [zhongjiedong/Tsukiro#31]
This is the only file I need to complete this modlist. I'm only asking what website, and who made the file so I can download this indescript mod. Please help!

**Comment by Corbillion** [comment]
Can get it from here ringo
https://mega.nz/file/RTZA2b4B#WcFLVQw8g0175FRTsskJASEVETWDkMMd4Rsi-JQ21X4

**Comment by ringostarsky1500** [comment]
Thank you so very much. I stayed up 4 hours searching yesterday!!! seriously thank a ton Corbillion! 

Hopefully this helps some other people as well.

Happy modding
