### ISSUE TITLE
nightingale armor

### ISSUE THREAD

**Issue by CDRShepard96** [zhongjiedong/Tsukiro#34]
npc's bodies dont show when they wear the armor
![SkyrimSE 2021-07-22 15-15-01 original](https://user-images.githubusercontent.com/71482465/126703896-4094b27e-1fcc-45ba-adfd-2041a73ab1ad.png)

**Comment by CDRShepard96** [comment]
nd to go along with this iv noticed in 2 or so quests the npcs glitch out nd they go to spots and stand there without doing wat they should to advance the quest.

**Comment by zhongjiedong** [comment]
i really cant do anything with this information. 

What 2 quests? What armour are both wearing?

**Comment by CDRShepard96** [comment]
one was maids 2 nd then the thiefs guild quests, but atm iv reloaded to a eailer save nd the armor seems to be fixed so will see if the advacing is fixed, but i seen on the maids mod that they say the npc mod glitches out the npc pathfinding, but thts all i know

**Comment by CDRShepard96** [comment]
there is one thing thts been annoying me when i go into first person to activate something it teleports me to the entrance of the place im in.

**Comment by zhongjiedong** [comment]
have you modified the modlist at all? What version are you running?

**Comment by CDRShepard96** [comment]
latest version nd i have some but it was doing it before i touched anything, iv reinstalled it today nd havent touched a thing nd still did it once

**Comment by CDRShepard96** [comment]
it only seemed to bug out when i was pulling a chain or lever, but sitting and opening doors works fine
