### ISSUE TITLE
Downloads Broken from Authored-Files.wabbajack.org

### ISSUE THREAD

**Issue by iamameme** [zhongjiedong/Tsukiro#35]
https://authored-files.wabbajack.org/bodyslideoutput0.7z_7878a94e-72b5-47e0-b104-a07c9f218b56/

`898.68 - Unable to download bodyslideoutput1.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/bodyslideoutput1.7z_a576f79a-f784-431e-8263-42bab9826f44)
898.68 - Unable to download bodyslideoutput3.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/bodyslideoutput3.7z_bb228086-c03a-443e-9487-c8df047dcbd8)
898.68 - Unable to download bodyslideoutput5.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/bodyslideoutput5.7z_eaa71e1c-1c98-4929-81ff-7b17b28c5be9)
898.68 - Unable to download bodyslideoutput7.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/bodyslideoutput7.7z_106ada15-86d8-4c8d-a71f-c780b08135b6)
898.68 - Unable to download EVW facegen021.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/EVW facegen021.7z_a68b65d5-119c-40ae-b230-33d00e9c97eb)
898.68 - Unable to download tsukirodyndolod043.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/tsukirodyndolod043.7z_eccaa385-1db2-46b2-b22c-7b7d1c1697fb)
`

Seems these downloads are broken. I get a "Forbidden" error when trying to access that URL to download it manually.

**Comment by zhongjiedong** [comment]
you cant download those manually they are CDN files. Try the network workaround in the wabbajack settings

**Comment by iamameme** [comment]
Hmmm, I tired the network workaround option and nothing changed.

**Comment by zhongjiedong** [comment]
try reducing your download threads to 1

**Comment by iamameme** [comment]
I tried reducing the download threads to 1, it didn't work, then tried reducing disk threads to 1, and that didn't work. Network workaround is also checked. Here is the log:

`867.05 - Found 1538 total files, 711 matching filesize
867.17 - Downloading Missing Archives
867.17 - Missing 6 archives
867.17 - Getting Nexus API Key, if a browser appears, please accept
867.17 - Loading server whitelist
867.21 - Loaded permissions for 469 servers and 235 Google Drive files
867.21 - File hash check (-42) 7cb8091b576c54ec17111e2a6f71cbb354e907f6b8bc84c4748aaf3d6a7188fb
867.29 - Downloading tsukirodyndolod043.7z
1044.08 - Trying to find solution to broken download for tsukirodyndolod043.7z
1044.08 - Looking for generic upgrade for 5gZ8pQg4qk8= (5740462284824381158)
1044.6 - No solution for broken download tsukirodyndolod043.7z WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/tsukirodyndolod043.7z_eccaa385-1db2-46b2-b22c-7b7d1c1697fb could be found
1044.6 - Downloading EVW facegen021.7z
1189.09 - Trying to find solution to broken download for EVW facegen021.7z
1189.09 - Looking for generic upgrade for yR99o/lspTs= (4297961238840549321)
1189.57 - No solution for broken download EVW facegen021.7z WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/EVW facegen021.7z_a68b65d5-119c-40ae-b230-33d00e9c97eb could be found
1189.57 - Downloading bodyslideoutput7.7z
1257.97 - Downloading bodyslideoutput5.7z
1320.38 - Trying to find solution to broken download for bodyslideoutput5.7z
1320.38 - Looking for generic upgrade for tXqDCQrY4uA= (-2241992126856201547)
1320.85 - No solution for broken download bodyslideoutput5.7z WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/bodyslideoutput5.7z_eaa71e1c-1c98-4929-81ff-7b17b28c5be9 could be found
1320.85 - Downloading bodyslideoutput3.7z
1382.2 - Trying to find solution to broken download for bodyslideoutput3.7z
1382.21 - Looking for generic upgrade for zqIE6GhcSiE= (2398831357167182542)
1382.76 - No solution for broken download bodyslideoutput3.7z WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/bodyslideoutput3.7z_bb228086-c03a-443e-9487-c8df047dcbd8 could be found
1382.76 - Downloading bodyslideoutput1.7z
1423.88 - Trying to find solution to broken download for bodyslideoutput1.7z
1423.88 - Looking for generic upgrade for yseZLqnHC5E= (-7995077184020953142)
1424.43 - No solution for broken download bodyslideoutput1.7z WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/bodyslideoutput1.7z_a576f79a-f784-431e-8263-42bab9826f44 could be found
1424.56 - Hashing Remaining Archives
1424.56 - Looking for files to hash
1424.71 - Found 1538 total files, 711 matching filesize
1633.35 - Unable to download bodyslideoutput1.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/bodyslideoutput1.7z_a576f79a-f784-431e-8263-42bab9826f44)
1633.35 - Unable to download bodyslideoutput3.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/bodyslideoutput3.7z_bb228086-c03a-443e-9487-c8df047dcbd8)
1633.35 - Unable to download bodyslideoutput5.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/bodyslideoutput5.7z_eaa71e1c-1c98-4929-81ff-7b17b28c5be9)
1633.35 - Unable to download EVW facegen021.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/EVW facegen021.7z_a68b65d5-119c-40ae-b230-33d00e9c97eb)
1633.35 - Unable to download tsukirodyndolod043.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/tsukirodyndolod043.7z_eccaa385-1db2-46b2-b22c-7b7d1c1697fb)
1633.35 - Cannot continue, was unable to download one or more archives
1633.35 - File hash check (-42) 7cb8091b576c54ec17111e2a6f71cbb354e907f6b8bc84c4748aaf3d6a7188fb
1633.38 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
1633.94 - File hash check (-42) 7cb8091b576c54ec17111e2a6f71cbb354e907f6b8bc84c4748aaf3d6a7188fb
`

**Comment by zhongjiedong** [comment]
then you have to try a VPN
