### ISSUE TITLE
A Few Questions

### ISSUE THREAD

**Issue by ringostarsky1500** [zhongjiedong/Tsukiro#37]
So first off, awesome modlist. I've been playing a while and it is just amazing. Personally I have some customization questions though:

1. how do I prevent my armor from being unequipped in combat with certain enemies. Sometimes, in combat they strike me and randomly my armor is unequipped! I'm not a fan, but I get why it's included. I play a male character and I can see this modlist is mainly for female characters mostly but I still want to play as a male. Suggestions?

2. How would I disable male on male sexlab animations? I can't seem to figure it out. I currently disabled sexlab and some dependent mods but I still get the notification for sexlab animations failed to play and sometimes npcs get stuck in the beginning of an animation that can't play which is super immersion breaking!  I can usually always play around this I would just like to see it gone :(

3. Is there any way to have sexlab and dependent mods enabled but limit it to male on female only with this modlist? No bandit males r***ing me for example. If not I'm fine with only having body physics which honestly is very awesome to see implemented like this.

In closing, thanks zhongjiedong for accomplishing what I never could with modding!

Thanks for any suggestions!

**Comment by zhongjiedong** [comment]
1. Disable Yamete for the player in the MCM
2. If Yamete is disabled it's very unlikely you're able to initiate any male on male animations
3. See above

**Comment by ringostarsky1500** [comment]
Thanks. I'll give it a try!
