### ISSUE TITLE
Wabbajack fails to download GS_SLAL and RyanReos Elf Paladin

### ISSUE THREAD

**Issue by Orthestral** [zhongjiedong/Tsukiro#38]
RyanReos Elf Paladin and GS_SLAL 11 07 downloads don't exist anymore.
GS has been updated and RyanReos Elf Paladin seems to have been deleted or something.

**Comment by zhongjiedong** [comment]
https://www.immyneedscake.com/skyrim-se-mods/ryanreos-elf-paladin

https://www.patreon.com/Gunslicer
