### ISSUE TITLE
Whiterun Thane/Lydia Missing ? 

### ISSUE THREAD

**Issue by Mayel3** [zhongjiedong/Tsukiro#40]
Hello ! Maybe i missed something but it seems that i'm unable to become thane of whiterun/Buy the House and get Lydia. I launch the game did some mod quest, the first dragon attacked me randomly near Riften did the quest for Astrid and Greybeard but it's seems to be no way to get Lydia and the house.

**Comment by zhongjiedong** [comment]
do the gildergreen quest

**Comment by Mayel3** [comment]
Ah ok ! Thanks you very much for your fast answers. I often play skyrim but rarely do that quest

**Comment by Criuion** [comment]
Doing the Gildergreen quest didn't give a thane title, and there is no clue on how to get the title.  Do i have to start the civil war quest? Already started the Dragon born quest.

**Comment by zhongjiedong** [comment]
need to buy breezehome too
