### ISSUE TITLE
Problem with Interior and Exterior Fog

### ISSUE THREAD

**Issue by ringostarsky1500** [zhongjiedong/Tsukiro#42]
[
![IMG_1377](https://user-images.githubusercontent.com/87745087/132116578-b94a1ea9-a3d3-4906-8fed-4a740d53f536.JPG)
![IMG_1379](https://user-images.githubusercontent.com/87745087/132116580-c0b7bb7e-fd0e-4c1c-848e-b2890d6b4f09.JPG)
![IMG_1378](https://user-images.githubusercontent.com/87745087/132116582-e4909347-fd24-4c74-8306-bd67964a60c1.JPG)
](url)

I'm unsure what has caused this type of fog to become this strange color, but I'm hoping you might know what enb setting I would need to change to have a more natural fog color. I played around in the enb a  while ago to tweak the settings for my monitor I just don't know what I could have done to change the fog color like this accidentally. I don't have a picture of this on the exterior but trust me it is the same thing mostly around bodies of water. I'm not even really sure this is enb related but it's what I suspect.

Just in case this is not enb related, Is there a way you know of I could disable this fog? The consol command SetFog 0,0 doesn't work so I'm out of ideas.

**Comment by zhongjiedong** [comment]
which version of the modlist is this?

**Comment by ringostarsky1500** [comment]
beta 0.8

**Comment by zhongjiedong** [comment]
this should be fixed in the latest release
