### ISSUE TITLE
Download failing

### ISSUE THREAD

**Issue by Joshi120** [zhongjiedong/Tsukiro#43]
Heya c:
i tried to install it now twice but it got stuck at "Bash Behaviors Overhaul"

after some digging it looks like the mod on the nexus got set to "Under moderation" mode since 2nd sept :/

could you possibly upload the missing mod to Mega.nz aswel? Thanks c:

https://www.nexusmods.com/skyrimspecialedition/mods/52633

**Comment by win4e7ter** [comment]
here try this https://www.nexusmods.com/skyrimspecialedition/mods/52633?tab=files&file_id=215675

**Comment by Joshi120** [comment]
Thanks a lot! This fixed this issue at least c:

but now i keep getting corrupted downloads even after multiple times deleting the affected files and redownloading them
so far they where:
Baka SOS female pubic hair addons expansion.7z
SOS - ERF - High Poly Addon BHUNP.7z

these 2 i was able to resolve by searching them up and just manualy downloading them but now i am stuck with this one

bodyslideoutput0.7z and i am sure more will come. i don't know whats going on :/

**Comment by zhongjiedong** [comment]
use the network workaround in wj settings

**Comment by Joshi120** [comment]
Thanks, i just gave it 2 trys but still the same result 
Maybe i am missing something elese in the log 
https://pastebin.com/n1MUwCNB

**Comment by zhongjiedong** [comment]
delete the tsukiro.wabbajack file and redownload

**Comment by Joshi120** [comment]
Heya c: 
After a LOT of redownloading of corrupted files over and over it finaly completed \o/ i got some nasty visual issues " a line going from the bottom of the screen to the top while moving" but i am sure i can fix this somehow c: Thank you for the help and your hard work on Tsukiro.
