### ISSUE TITLE
Two hand sword 3 hit attack animation 

### ISSUE THREAD

**Issue by LutherTheDandy** [zhongjiedong/Tsukiro#46]
### What happened?

when I use the two hand sword m1+m2 attack, the animation and sound seems off. Sometime I click m1+m2 it perform the 5 hit attack, but other time it perform 3 hit attack with a broken animation. I did edit the character scale, but even with the normal scale with both gender, the animation is still broken.

![20211018140235_2](https://user-images.githubusercontent.com/92709803/137678975-249c88ce-f883-4483-9558-4dae27e0eaa9.jpg)

### Modlist version

1.07

**Comment by zhongjiedong** [comment]
what twohanded skill level and what twohanded perks please?

**Comment by zhongjiedong** [comment]
fixed for next update
