### ISSUE TITLE
How can i make my own bodyslide preset? Whats all the bodyslideoutputfiles in the pluginlist?

### ISSUE THREAD

**Issue by SHIIIZA117** [zhongjiedong/Tsukiro#48]
### What happened?

i would like to make my charecter more curvy and change the sliders of the body and the armor. but when i enter bodyslide. there are no presets for all the armors you added.

best regards

SHIIIZA117

### Modlist version

latest version

**Comment by zhongjiedong** [comment]
read the full guide
