### ISSUE TITLE
Dual wield slowmotion

### ISSUE THREAD

**Issue by hadluk** [zhongjiedong/Tsukiro#49]
### What happened?

When using dual wield and right after choosing the perk "Dual Flurry" in the "one-handed" tree the attacks slow down by atleast 75% instead of increasing by 20%. It still works if I unequip one weapon but not with two one handed weapons. It was at a normal attack speed before taking dual flurry and working using two one handed.

### Modlist version

1.1.0

**Comment by zhongjiedong** [comment]
still happen after restarting the game?

**Comment by zhongjiedong** [comment]
Fixed in 1.1.1
