### ISSUE TITLE
Priestess Outfit

### ISSUE THREAD

**Issue by CDRShepard96** [zhongjiedong/Tsukiro#50]
only the high priestess leotard shows, and other 2 make the body go invisible
![SkyrimSE 2021-10-30 20-36-54 original](https://user-images.githubusercontent.com/71482465/139563203-9fcb8e41-f027-4daf-9e4a-472603990c06.png)
![SkyrimSE 2021-10-30 20-36-57 original](https://user-images.githubusercontent.com/71482465/139563204-a06cdef7-f5ae-4d98-9a62-53e336615e59.png)
![SkyrimSE 2021-10-30 20-37-00 original](https://user-images.githubusercontent.com/71482465/139563206-ac1ba94c-1726-48bd-9958-10293080fff8.png)

**Comment by zhongjiedong** [comment]
this is not  a bug, you cheated these items in

**Comment by CDRShepard96** [comment]
seen new clothing so had to see wat they looked like ¯\_(ツ)_/¯
