### ISSUE TITLE
Animation hitboxes

### ISSUE THREAD

**Issue by Sinastrax** [zhongjiedong/Tsukiro#51]
### What happened?

Greataxe, no lvl, no perks: the LT+RT (should be M1+M2) powerattack hits multiple times even if it is only 1 swing and has insane hyperarmor
Enemy Unarmed multihit powerattack has pretty bad hitboxes and doesn't hit me unless I'm in kissing range
can't say anything about lvl or perks since it's the enemy

### Modlist version

beta 1.1

**Comment by zhongjiedong** [comment]
Fixed in 1.1.1
