### ISSUE TITLE
Unable to complete 1.1.1 download due to missing file

### ISSUE THREAD

**Issue by Origins101** [zhongjiedong/Tsukiro#53]
### What happened?

Unable to pull Shire Facegen (https://authored-files.wabbajack.org/Shire facegen.7z_fe7c3e10-0e6c-4535-b87b-6537bc3a043e) "Cannot continue, was unable to download one or more archive. Unable to browse to location (if that even is a thing, but shows as 404)

This leads to failed install.

See attached log

[Wabbajack.current.log](https://github.com/zhongjiedong/Tsukiro/files/7455532/Wabbajack.current.log)

### Modlist version

1.1.1 Beta

**Comment by zhongjiedong** [comment]
delete your tsukiro.wabbajack file and try again

**Comment by Origins101** [comment]
confirmed working now
