### ISSUE TITLE
Can't download 1 file

### ISSUE THREAD

**Issue by SirSockingham** [zhongjiedong/Tsukiro#54]
11,12 - Found 861 total files, 822 matching filesize
11,2 - Unable to download Shire facegen.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/Shire facegen.7z_fe7c3e10-0e6c-4535-b87b-6537bc3a043e)
11,2 - Cannot continue, was unable to download one or more archives

**Comment by zhongjiedong** [comment]
delete your tsukiro.wabbajack file and try again
