### ISSUE TITLE
Unable to Exit bandit tent outside Mzinchaleft

### ISSUE THREAD

**Issue by Dusk-Mage** [zhongjiedong/Tsukiro#55]
### What happened?

Facing North, the Tent on the right at the top of the stairs leading down to the dungeon will let you inside.  There is a tankard and what appears to be a note on the table (I was unable to interact with the note).
When trying to exit the tent I was unable to do so and had to tcl out.
![image](https://user-images.githubusercontent.com/19332882/140508411-e97e78d3-c879-431b-b3c0-5409695c9476.png)

### Modlist version

Version 1.1.1

**Comment by zhongjiedong** [comment]
couldnt reproduce
