### ISSUE TITLE
Greatsword throwing two attacks instead of one in Third Person.

### ISSUE THREAD

**Issue by TraxitG** [zhongjiedong/Tsukiro#57]
### What happened?

1. Greatsword
2. Two-Handed - 40
3. Two-Handed Mastery, Brutal Fighter, Ferocious Strength(*)

(*)I suspect this may be the perk causing the issue.

After some mild testing, it seems this only applies to the normal(default) _first_ attack(LMB). The second attack in the chain dishes out a single hit accordingly. As well as the alternate attack dishing out four. Power-Attacks behave normally.

### Modlist version

1.1.3.3

**Comment by zhongjiedong** [comment]
Fixed in 1.15
