### ISSUE TITLE
Auri is insanely overpowered right off the bat.

### ISSUE THREAD

**Issue by TraxitG** [zhongjiedong/Tsukiro#58]
### What happened?

As the title exclaims. I picked up Auri at roughly level 5 and literally at my first combat encounter I see Auri dealing 400 damage to some giant spriggan creature. Alternatively, she would do ~200 damage to humanoid/armoured targets.

### Modlist version

1.1.3.3

**Comment by zhongjiedong** [comment]
should be more balanced now, removed all her starting perks
