### ISSUE TITLE
Danica Pure-Spring seems to have lost her clothes

### ISSUE THREAD

**Issue by Dusk-Mage** [zhongjiedong/Tsukiro#59]
### What happened?

After updating and visitng White run for the first time on a new save, Danica seems to have lost her clothing.  It is Equiped but does not show up.
![image](https://user-images.githubusercontent.com/19332882/143778397-92e165d5-2f65-49d7-b229-ba0d0a9f3962.png)

### Modlist version

1.1.54

**Comment by Dusk-Mage** [comment]
I stand corrected, she is missing parts of the set.
![image](https://user-images.githubusercontent.com/19332882/143778678-8625bf64-ff91-4570-bf46-921c7a4adac0.png)

**Comment by Dusk-Mage** [comment]
Leaving town and coming back fixed this issue.

**Comment by Dusk-Mage** [comment]
Issue still persists on all NPCs wearing this armor set. When they leave the area they spawn in they redress.

**Comment by zhongjiedong** [comment]
fixed in 1.1.691 reverting to Schlongs of Skyrim dll
