### ISSUE TITLE
"The Way to a big oaf's Heart" needs a Scroll of Toxic Cloud to continue not Bane Undead

### ISSUE THREAD

**Issue by Dusk-Mage** [zhongjiedong/Tsukiro#60]
### What happened?

There is an ID conflict between 3NPC and Odin.
The quest "The Way to a big oaf's Heart" Starts from the NPC Callen in Nightgate.
The quest calls for a Scroll of Bane undead, Odin replaces this with Toxic cloud.  If you use the player.AddItem 000A44C5 1 to spawn in the Scroll of Bane Undead you get a scroll of Toxic cloud.
However because the quest checks the item ID it will accept the scroll of toxic cloud in place of the scroll of Bane Undead

### Modlist version

1.1.54

**Comment by zhongjiedong** [comment]
![2021-12-05 21_24_01-SSEEdit 4 0 4 x64](https://user-images.githubusercontent.com/20669755/144764472-01b5ee89-723b-4ef8-98bc-bcaa7db6482b.png)

I think its named the same?

**Comment by Dusk-Mage** [comment]
When I spawned the scroll in by ID, looking up the item ID the game gave me a Scroll of toxic cloud, which worked for the quest.
![image](https://user-images.githubusercontent.com/19332882/145450336-ec0b42e0-3d93-417b-af8e-995365b947ae.png)

Looking at the Entry for Item 000A44C5 I can see Odin replaces the 'Scroll of Repel Undead' with 'Scroll of Toxic Cloud'.

Makes sense the quest would look at the FormID and not the name to see if it was in the player inventory.
![image](https://user-images.githubusercontent.com/19332882/145451153-067bba7a-9726-45df-b88d-4e49551ce09a.png)

**Comment by zhongjiedong** [comment]
Will edit the quest text so it reflects the scrolls in the modlist

**Comment by zhongjiedong** [comment]
Fixed in 1.1.64
