### ISSUE TITLE
Naked NPC's.

### ISSUE THREAD

**Issue by Asmondar** [zhongjiedong/Tsukiro#63]
### What happened?

I went to Winterhold and Jora was only wearing a habit and boots. Great for the bedroom, but a little bit cold for everyday outer ware. I'm on an older version, but I read somewhere that other NPC's were naked too, so figuired I"d put this in to remind you of the fact that some npc's are still naked. Senna I think too.

### Modlist version

It says 1.1.54

**Comment by zhongjiedong** [comment]
fixed in 1.1.691 reverting to Schlongs of Skyrim dll
