### ISSUE TITLE
Hotkeying "Knights Shield" from Darkend with SkyUI 'Q' causes CTD

### ISSUE THREAD

**Issue by Dusk-Mage** [zhongjiedong/Tsukiro#65]
### What happened?

When you favorite and got to hotkey the Item "knights Shield" from Darkened (Found in abandoned mansion) it triggers a CT
[Crash_2021_12_9_12-49-55.txt](https://github.com/zhongjiedong/Tsukiro/files/7687359/Crash_2021_12_9_12-49-55.txt)
[Crash_2021_12_8_21-51-1.txt](https://github.com/zhongjiedong/Tsukiro/files/7687362/Crash_2021_12_8_21-51-1.txt)
D

### Modlist version

1.1.63

**Comment by zhongjiedong** [comment]
Cannot reproduce
