### ISSUE TITLE
Unable to download Lover**** mods directly from Wabbajack

### ISSUE THREAD

**Issue by ichxorya** [zhongjiedong/Tsukiro#73]
### What happened?

Since Wabbajack still having problem with Lover**** account and downloads, I hope you can put those mods to the "Commonly failing downloads" part of the readme.

### Modlist version

1.1.69

**Comment by zhongjiedong** [comment]
you can always find the full manifest file posted on the releases section: https://github.com/zhongjiedong/Tsukiro/releases
