### ISSUE TITLE
Suggested DAR animations for the ModPack

### ISSUE THREAD

**Issue by Dusk-Mage** [zhongjiedong/Tsukiro#78]
I would like to suggest the following DAR animations.

Bow Animations: https://www.nexusmods.com/skyrimspecialedition/mods/61157
I installed this one and While it is female only I really enjoy the fact that the animation draws the arrow as part of the knock and does not walk around with an arrow floating behind the female hands.

Swimming Animations: https://www.nexusmods.com/skyrimspecialedition/mods/61160
The Mermaid swim looks really nice in game, flows well, just needs a tail ;)

Both of the file links lack any real visual of how these work but so far I like them.

**Comment by zhongjiedong** [comment]
both now added as of 1.1.72
