### ISSUE TITLE
Weapons are invisible in first person.

### ISSUE THREAD

**Issue by Bar2co** [zhongjiedong/Tsukiro#79]
### What happened?

Only bows show up.
And the dwarven gauntlets from book of uunp iron and steel are invisible too.
Base form: 490011F6
Ref Form:FF017D67
Also I recomend adding AddItemMenu because some items disapear into the void when we drop them

### Modlist version

1.1.694

**Comment by zhongjiedong** [comment]
which weapons? Every single one? Did you make any changes to the modlist as I cannot reproduce

**Comment by Bar2co** [comment]
I restarted after adding AddItemMenu to test more mods and it fixed it. I already tried restarting without any change and it didn't work. I don't know why. I didn't add a mod to the modpack

**Comment by Bar2co** [comment]
Gauntlets are still invisible tho

**Comment by zhongjiedong** [comment]
well adding additemmenu is adding mods to the pack, getting items from that is not supported. I will see about the gauntlets

**Comment by zhongjiedong** [comment]
fixed in 1.1.72
