### ISSUE TITLE
Choosing the Investor perk fails to adjust the intended global variable for most vendors, fix included

### ISSUE THREAD

**Issue by Kathaarian** [zhongjiedong/Tsukiro#80]
### What happened?

For whatever reason the variable fails to change properly for most vendors (or rather they're just set wrong to begin with): in my case, it was almost all vanilla vendors with the exception of Sybille Stentor in Solitude (PerkInvestorSolitudeMagic), and a few others - this can be checked by typing help investor into the console after choosing the perk and seeing which ones are set to 100. 

A roundabout way to fix this is by just setting the variables manually, I have attached the text file that includes all the vanilla merchants, users could possibly run it by just typing 'bat investor' into the command console once they have acquired the perk; file needs to be in Tsukiro Stock Game folder of course. The change will persist through reloads as well. Alternatively, you could bake this into the starting save since even if the variable is set to 100, without the perk the dialogue shouldn't appear but I didn't test that, personally.

[investor.txt](https://github.com/zhongjiedong/Tsukiro/files/7922089/investor.txt)
 

### Modlist version

1.1.691

**Comment by zhongjiedong** [comment]
fixed in 1.01
