### ISSUE TITLE
Unchecked mods and plugins

### ISSUE THREAD

**Issue by jdkbph** [zhongjiedong/Tsukiro#83]
Hello. I installed Tsukiro and everything went well. When I opened ModOrganizer I noticed that there are a couple of dozen mods and esps unchecked. For example: 

JK's stuff, Lux stuff, Great town of Karthwasten and Shor's Stone, etc. among the ESPs on the right side.

Paper Blackreach Map, Revna preset, Thieves night on the town, XPMSSE - Nemesis - Papyrus STack Fix, etc on the left side.

Are these supposed to be unchecked for some reason, or should I activate all of them?

Thanks

MO v2.4.4 BTW.

**Comment by zhongjiedong** [comment]
No that shouldn't be the case, reinstall the list

**Comment by jdkbph** [comment]
That helped. Thank you.
