### ISSUE TITLE
Wabbajack Issues

### ISSUE THREAD

**Issue by DrOfDarkness898** [zhongjiedong/Tsukiro#84]
### What happened?

This issue may seem to be an issue for the Wabbajack forumn, however I'm sure I speak for others when I say that though a powerful tool, it would be a great aid to not have to work around the issues presented by wabbajack.

Specifically, the fact that the software seems to break for many when it comes to downloading mods from LoversLab.
My suggested fix for people is that someone, I.e. one of you fine people, simply list all the mods that are downloaded for Tsukiro form Loverslab.
That way people can go and download them themselvs and move the .zip files straight into the downloaded mods folders.

If anyone could do this for me that would be great, it's my second time downloading Tsukiro and I ran into this issue the first time and I cant work out how I got around it.

### Modlist version

The most recent one as of 08/02/2022.
I don't know what version that would be

**Comment by zhongjiedong** [comment]
It's a temporary issue with the LL site. Regardless the manifest file with
the links for all mods are always included with every release on github
