### ISSUE TITLE
Installing on Wabbajack, two files missing.

### ISSUE THREAD

**Issue by LeoLameous** [zhongjiedong/Tsukiro#86]
### What happened?

Unable to download
[COCO] Pinup Cheongsam [SE] - BHUNP.7z
Smooth Motion Pack SE 5.3.3.FOMOD
[Wabbajack.current.log](https://github.com/zhongjiedong/Tsukiro/files/8181776/Wabbajack.current.log)
d

### Modlist version

v6.2.0

**Comment by zhongjiedong** [comment]
read the readme

**Comment by LeoLameous** [comment]
Thank you I looked for like two hours and don’t see that button.
