### ISSUE TITLE
not able to install Reliquary of Myth - Artifact Overhaul

### ISSUE THREAD

**Issue by CDRShepard96** [zhongjiedong/Tsukiro#9]
file hash check fails everytime it checks the hash for Reliquary of Myth
![Wabbajack_2021-06-18_18-15-11](https://user-images.githubusercontent.com/71482465/122623325-3ab0c300-d061-11eb-95e1-4621f755ddbb.png)

**Comment by zhongjiedong** [comment]
try again

**Comment by CDRShepard96** [comment]
iv tried about 12 times since last night. nd same error.

**Comment by zhongjiedong** [comment]
yeah I just did something, so try again

**Comment by CDRShepard96** [comment]
still an error, nd i noticed when it brings me to the page to download it doesn't highlight the download for that mod, which i though was odd.

**Comment by zhongjiedong** [comment]
looks like nexus is having issues with those files at the moment you'll have to wait

**Comment by CDRShepard96** [comment]
alright, at first i was thinking cuz it was v3.9.1
