### ISSUE TITLE
How to re-enable the NEW GAME option?

### ISSUE THREAD

**Issue by hamletsdead** [zhongjiedong/Tsukiro#93]
I tried your modpack and liked it fine, but ended up reverting to 1.5.97, reinstalling MO2 on a different directory, and moving a bunch of mods to my new modlist. When I launched the game tonight there was no "new game" option and I got the popup to load your old save from the Tsukiro modpack. Really appreciate it if you could tell me how to get my menu screen back to normal, as somehow your Wabbajack pack hijacked my game.

**Comment by zhongjiedong** [comment]
if  you moved the "all in one 60 fps" mod over thats the one disabling new game
