### ISSUE TITLE
SLAL_Billyy_Animationsv5.4SE.zip no longer available

### ISSUE THREAD

**Issue by bobbinbette** [zhongjiedong/Tsukiro#94]
### What happened?

572890882_SLAL_Billyy_Animationsv5.4SE.zip is currently required but the download page was updated 1 day ago and is no longer available. The mod has been bumped to version 5.5SE. 

### Modlist version

Whichever version of the modlist is displayed in Wabbajack as of 4/2/2022

**Comment by zhongjiedong** [comment]
There's a temporary download link on the discord server
