### ISSUE TITLE
Tsukiro - will not download

### ISSUE THREAD

**Issue by ejr1216** [zhongjiedong/Tsukiro#96]
### What happened?

A bug happened!I am stuck with Tsukiro not being able to download a file that was updated 2 days ago.  billy_animationsv5.4se download current version is 5.5se and they removed the 5.4 archive.
NEW

### Modlist version

current verison

**Comment by zhongjiedong** [comment]
there is a temporary download linked in the discord server

**Comment by ejr1216** [comment]
I do not see #Tsukiro as a channel

**Comment by zhongjiedong** [comment]
https://github.com/zhongjiedong/Tsukiro/wiki/FAQ discord link at the bottom

**Comment by ejr1216** [comment]
tyvm
