### ISSUE TITLE
Welcome to Tsukiro popup?

### ISSUE THREAD

**Issue by hamletsdead** [zhongjiedong/Tsukiro#97]
Sorry to bug you again on trivial issues, but I can't get the Welcome to Tsukiro popup to go away. Don't get me wrong, I love the modpack you put together, and you saved me countless hours redownloading my 800+ mod load order and installing it. But I've removed so many mods from the pack and added so many other mods that it's not really the Tsukiro pack anymore. I can't figure out how to get rid of the popup in the interface menu, so any help would be greatly appreciated.

**Comment by YoYoK3nny** [comment]
This doesn't seem like something you'll get official help for (since you've modified the pack from what is the intended experience), but "Press Enter" is the mod that does that prompt.
