### ISSUE TITLE
Breezehome interior door broke, but easily fixed

### ISSUE THREAD

**Issue by Criuion** [zhongjiedong/Tsukiro#98]
Hi,

Breezehomes interior door is missing it's teleport destination for getting back outside.  You can activate the door but it just swings open and closed.

navpatch.esp is missing the teleport information, it is easily fixed by adding the information in from hearthfire.esm, added image to show where i added the info to fix it.

![Untitled](https://user-images.githubusercontent.com/53840981/162276756-0a6b1ed8-7d76-4341-ab20-b0c6096f18c6.png)

Don't know about the missing Navigation door link, thought i'd leave it alone since the plugin is called nav patch and i might undo a fix by adding the nav mesh info back.

**Comment by zhongjiedong** [comment]
there's a fixed navpatch for this in the discord server pins if you still need this. Will obviously be fixed in next update
