### ISSUE TITLE
SLAL billy 

### ISSUE THREAD

**Issue by wolfoxo** [zhongjiedong/Tsukiro#99]
### What happened?

i down loader SLAL billy manually and still is not recognized by the mod list .
i cheeked the manifest to make sure the file names match and still .

### Modlist version

Tsukiro - Boobies Bounce Thrice beta 1.1.7
![iss](https://user-images.githubusercontent.com/104327364/164999301-2acba94c-dce1-46ac-a043-bb1ab7d25f5f.jpg)
4

**Comment by zhongjiedong** [comment]
there is a temporary download link on the tsukiro discord: https://discord.gg/jolly-coop

**Comment by wolfoxo** [comment]
i opend discord as i looked for an answer but cant locate the file .
can please help .
( new user of discord )
